<p align="center">
<img src="https://github.com/cristiandarioortegayubro/BDS/blob/main/images/Logo%20Pandas.png?raw=true">
</p>

 # **<font color="#07a8ed">Historia y evolución de Pandas 🐼 </font>**

<p align="justify">
💗 La historia y evolución de Pandas es notable en el contexto de Business Data Science, ya que se ha convertido en una de las herramientas más populares y poderosas para el análisis de datos en Python.
<br><br>
Aquí está un resumen de su historia y su relevancia en el ámbito de Business Data Science:
<br><br>

1. **Orígenes de Pandas:**
   Pandas fue desarrollado inicialmente por Wes McKinney mientras trabajaba en AQR Capital Management en 2008. En ese momento, McKinney buscaba una herramienta eficiente para el análisis de datos en Python que pudiera manejar conjuntos de datos de tamaño variable con facilidad. Inspirado por el trabajo que había realizado en finanzas cuantitativas, McKinney creó Pandas para satisfacer estas necesidades.

2. **Lanzamiento y adopción temprana:**
   Pandas fue lanzado como un proyecto de código abierto en 2009 y rápidamente ganó popularidad dentro de la comunidad de Python debido a su capacidad para manipular y analizar datos de manera eficiente. La sintaxis clara y expresiva de Pandas, inspirada en lenguajes como R y SQL, facilitó su adopción por parte de analistas y científicos de datos.

3. **Evolución y crecimiento:**
   A lo largo de los años, Pandas ha experimentado un crecimiento significativo en términos de características, rendimiento y estabilidad. Se han agregado numerosas funcionalidades nuevas, como la capacidad de manejar datos de series temporales, realizar operaciones de agrupamiento y pivotar datos de manera eficiente. Además, se han realizado mejoras continuas en el rendimiento y la optimización del código para manejar conjuntos de datos cada vez más grandes.

4. **Relevancia en Business Data Science:**
   Pandas se ha convertido en una herramienta fundamental en el campo de Business Data Science debido a varias razones:

   - **Facilidad de uso:** La sintaxis intuitiva y expresiva de Pandas facilita la manipulación y el análisis de datos, lo que permite a los profesionales de negocios realizar tareas complejas con relativa facilidad.
   
   - **Capacidad para manejar datos estructurados:** Pandas es especialmente eficaz para trabajar con datos tabulares y estructurados, como los que se encuentran comúnmente en el entorno empresarial. Esto lo hace ideal para tareas como limpieza de datos, transformación y análisis exploratorio.
   
   - **Integración con otras herramientas:** Pandas se integra bien con otras herramientas populares en el ecosistema de Python, como NumPy, Matplotlib y Scikit-learn, lo que permite construir y desplegar pipelines de análisis de datos completos.

<br>
<p align="justify">
 👀 En resumen, Pandas ha evolucionado desde sus humildes comienzos hasta convertirse en una herramienta indispensable de cualquier profesional de Business Data Science. Su capacidad para manejar datos de manera eficiente y su facilidad de uso lo hacen invaluable para realizar análisis de datos empresariales y tomar decisiones informadas basadas en datos.

 # **<font color="#07a8ed">Conociendo Pandas</font>**

<p align="justify">
El módulo <code>Pandas</code> es una herramienta importante en el desarrollo de los siguientes notebooks. Contiene estructuras de datos y herramientas de manipulación de datos para que la limpieza y el análisis de datos sea rápido. <br><br> <code>Pandas</code> usualmente se usa en conjunto con herramientas de computación numérica como <code>NumPy</code> y como <code>SciPy</code>. Tambien con bibliotecas analíticas como <code>statsmodels</code> y <code>scikit-learn</code> y bibliotecas de visualización de datos como <code>seaborn</code> y <code>plotly</code>. <br><br> <code>Pandas</code> adopta partes significativas del estilo idiomático de <code>NumPy</code>, especialmente funciones basadas en matrices y una preferencia por el procesamiento de datos sin bucles <code>for</code>.<br><br> Mientras que <code>Pandas</code> adopta muchos modismos de <code>NumPy</code>, la mayor diferencia que tienen ambos módulos es que <code>Pandas</code> está diseñado para trabajar con datos tabulares o heterogéneos mientras que <code>NumPy</code>, por el contrario, es el más adecuado para trabajar con datos de matrices numéricas homogéneas.Desde que se convirtió en un proyecto de código abierto en 2010, <code>Pandas</code> ha madurado hasta convertirse en una biblioteca bastante grande que es aplicable en un amplio conjunto de casos de uso del mundo real. La comunidad de desarrolladores y usuarios de <code>Pandas</code> han sido una parte clave de su éxito.
</p>

<p align="justify"> 👀 Por convención, de esta manera se importa <code>Pandas</code>:  </p>

In [ ]:
import numpy as np
import pandas as pd

<p align="justify"> 👀 Versión de <code>Pandas</code>:  </p>

In [ ]:
print(pd.__version__)

2.2.2

Imprime la versión de la biblioteca Pandas que está instalada en el entorno. Esto es útil para asegurar la compatibilidad del código.

<p align="justify"> 👀 Versión de <code>Numpy</code>:  </p>

In [ ]:
print(np.__version__)

2.0.2

Imprime la versión instalada de la biblioteca NumPy.

 # **<font color="#07a8ed">Estructuras de datos</font>**

<p align="justify">
Las estructuras de datos que debemos manejar son: <code>Series</code> y <code>DataFrame</code>. Si bien no son una solución universal para todos los problemas que se pueden plantear, proporcionan una base sólida para una amplia variedad de tareas de datos. Estas estructuras de datos son fundamentales en <code>Pandas</code>.
</p>

 ## **<font color="#07a8ed">Serie</font>**

<p align="justify">
Una serie es un objeto unidimensional similar a una matriz que contiene una secuencia de valores (similares a los tipos NumPy) del mismo tipo y una matriz asociada de etiquetas de datos, denominada índice. <br><br> La serie más simple se forma a partir de solo una matriz de datos:</p>

<p align="center">
<img src="https://github.com/cristiandarioortegayubro/BDS/blob/main/images/Image_0005.jpg?raw=true" width="600" height="">
</p>

<p align="justify"> 👀
Con el método <code>Series()</code> de <code>Pandas</code> creamos la serie, solamente pasando una lista de elementos (del mismo tipo de datos) podemos crear nuestra serie, y luego podemos asignar esta serie a un objeto. Para verla, solamente llamamos al objeto.
</p>

In [ ]:
serie = pd.Series([7, 9, 5], name="numeros")

Crea una estructura de datos fundamental de Pandas llamada Serie. Una Serie es como una columna en una tabla o un arreglo unidimensional. En este caso, contiene los números 7, 9, 5 y se le asigna el nombre "numeros".

In [ ]:
serie

0    7
1    9
2    5
Name: numeros, dtype: int64

Muestra el contenido de la Serie. A la izquierda aparece el índice (que por defecto es una secuencia de enteros 0, 1, 2) y a la derecha los valores.

<p align="justify"> 👀
La representación de una serie que se muestra interactivamente muestra el índice a la izquierda y los valores a la derecha. Como no especificamos un índice para los datos, se crea uno predeterminado que consiste en valores enteros. <br><br>Para obtener una representación de matriz, se usa el atributo <code>array</code> y para visualizar el indice de los elementos de la serie, se usa el atributo <code>index</code>.
</p>

In [ ]:
serie.array

<NumpyExtensionArray>
[np.int64(7), np.int64(9), np.int64(5)]
Length: 3, dtype: int64

Accede al atributo .array, que devuelve los valores de la Serie en una estructura similar a un arreglo de NumPy.

In [ ]:
serie.index

RangeIndex(start=0, stop=3, step=1)

Accede al atributo .index, que muestra el objeto que define el índice de la Serie. En este caso, es un RangeIndex que va de 0 a 3 (sin incluir el 3).

<p align="justify"> 👀
Puede ser que se quiera crear una serie con un índice que identifique cada punto de datos con una etiqueta. Por ejemplo:
</p>

In [ ]:
indice = pd.Series([40, 42, 45, 43], index=["d", "b", "a", "c"], name="cuarentas")

Crea una nueva Serie, pero esta vez se especifica un índice personalizado usando etiquetas de texto ("d", "b", "a", "c") en lugar del índice numérico por defecto.

In [ ]:
indice

d    40
b    42
a    45
c    43
Name: cuarentas, dtype: int64

Muestra la Serie indice, donde ahora las etiquetas personalizadas aparecen a la izquierda.

In [ ]:
indice.index

Index(['d', 'b', 'a', 'c'], dtype='object')

Muestra el objeto índice de la Serie, que ahora es de tipo Index y contiene las etiquetas de texto.

In [ ]:
"b" in indice

True

In [ ]:
"h" in indice

False

Estas celdas comprueban si una etiqueta específica existe en el índice de la Serie. Devuelven True si la etiqueta está presente y False si no lo está.

<p align="justify"> 👀
Si tenemos los datos contenidos en un diccionario, entonces se puede crear una serie. Por ejemplo:
</p>

In [ ]:
ESP = {"Activo": 35000, "Pasivo": 10000, "Patrimonio Neto": 25000}

Crea un diccionario de Python estándar, donde las claves son cadenas de texto y los valores son números enteros.

In [ ]:
type(ESP)

dict

Verifica que el tipo de dato de la variable ESP es dict (diccionario).

In [ ]:
serie_ESP = pd.Series(ESP, name="ESP")

Crea una Serie a partir de un diccionario. Pandas automáticamente utiliza las claves del diccionario como el índice de la Serie y los valores del diccionario como los valores de la Serie.

In [ ]:
serie_ESP

Activo             35000
Pasivo             10000
Patrimonio Neto    25000
Name: ESP, dtype: int64

Muestra la Serie serie_ESP creada a partir del diccionario.

In [ ]:
serie_ESP.iloc[0]

np.int64(35000)

Accede al valor de la Serie usando .iloc, que permite seleccionar datos por su posición entera (índice posicional). iloc[0] devuelve el primer elemento de la Serie (35000).

In [ ]:
serie_ESP.iloc[0] == serie_ESP.iloc[1] + serie_ESP.iloc[2]

np.True_

Realiza una comprobación de la ecuación patrimonial (Activo = Pasivo + Patrimonio Neto) accediendo a los valores de la Serie por su posición. El resultado es True.

<p align="justify"> 👀
Y una serie puede convertirse en diccionario con el metodo <code>to_dict()</code>. Por ejemplo:
</p>

In [ ]:
serie_ESP.to_dict()

{'Activo': 35000, 'Pasivo': 10000, 'Patrimonio Neto': 25000}

Utiliza el método .to_dict() para convertir la Serie de Pandas de nuevo a un diccionario de Python.

In [ ]:
serie_DICT = serie_ESP.to_dict()

In [ ]:
type(serie_DICT)

dict

Asigna el diccionario convertido a la variable serie_DICT y luego confirma que su tipo es dict.

 ## **<font color="#07a8ed">DataFrame</font>**

<p align="justify">
Un DataFrame representa una tabla de datos y contiene una colección ordenada y con nombre de columnas, cada una de las cuales puede ser un tipo de valor diferente (numérico, cadena, booleano, etc.). El DataFrame tiene un índice de fila y columna.
</p>

<p align="center">
<img src="https://github.com/cristiandarioortegayubro/BDS/blob/main/images/Image_0007.jpg?raw=true"width="600" height="">
</p>

<p align="justify"> 👀
Si bien un DataFrame es físicamente bidimensional, puede usarlo para representar datos de dimensiones superiores en un formato tabular utilizando la indexación jerárquica... Hay muchas maneras de construir un DataFrame, aunque una de las más comunes es desde un diccionario de listas de igual longitud o matrices <code>NumPy</code>.
</p>

In [ ]:
ventas = [230.1, 44.5, 17.2, 151.5, 180.8]
periodico = [22.1, 10.4, 9.3, 18.5, 12.9]
radio = [37.8, 39.3, 45.9, 41.3, 10.8]
tv = [69.2, 45.1, 69.3, 58.5, 58.4]

Crea cuatro listas de Python con datos numéricos que representan inversiones en publicidad y ventas.

In [ ]:
diccionario = {"Ventas":ventas,
               "Radio":radio,
               "Tv":tv,
               "Periodico":periodico}

Crea un diccionario donde las claves serán los nombres de las columnas y los valores son las listas de datos creadas anteriormente.

In [ ]:
df = pd.DataFrame(diccionario)

Crea la segunda estructura de datos fundamental de Pandas, el DataFrame. Un DataFrame es una tabla bidimensional (similar a una hoja de cálculo) donde las columnas tienen nombres y las filas tienen un índice. Se crea a partir del diccionario.

In [ ]:
df

   Ventas  Radio    Tv  Periodico
0   230.1   37.8  69.2       22.1
1    44.5   39.3  45.1       10.4
2    17.2   45.9  69.3        9.3
3   151.5   41.3  58.5       18.5
4   180.8   10.8  58.4       12.9

Muestra el DataFrame resultante.

<p align="justify"> 👀
A la hora de la creacion del DataFrame se puede especificar el orden de las columnas. <br><br>Por ejemplo:
</p>

In [ ]:
df = pd.DataFrame(diccionario, columns=["Ventas","Periodico", "Radio", "Tv"])

Vuelve a crear el DataFrame, pero esta vez utiliza el argumento columns para especificar el orden deseado de las columnas.

In [ ]:
df

   Ventas  Periodico  Radio    Tv
0   230.1       22.1   37.8  69.2
1    44.5       10.4   39.3  45.1
2    17.2        9.3   45.9  69.3
3   151.5       18.5   41.3  58.5
4   180.8       12.9   10.8  58.4

Muestra el DataFrame con las columnas en el nuevo orden especificado.

<p align="justify"> 👀
Si se coloca una columna que no estaba, entonces aparece con valores nulos en el DataFrame. Por ejemplo:
</p>

In [ ]:
df = pd.DataFrame(diccionario, columns=["Ventas", "Periodico", "Radio", "Tv", "Medios"])

Crea de nuevo el DataFrame, pero incluye en la lista de columnas un nombre ("Medios") que no existe en el diccionario original.

In [ ]:
df

   Ventas  Periodico  Radio    Tv Medios
0   230.1       22.1   37.8  69.2    NaN
1    44.5       10.4   39.3  45.1    NaN
2    17.2        9.3   45.9  69.3    NaN
3   151.5       18.5   41.3  58.5    NaN
4   180.8       12.9   10.8  58.4    NaN

Muestra el DataFrame. Pandas crea la columna "Medios" y, al no tener datos para ella, la rellena con valores NaN (Not a Number), que es el indicador estándar de datos faltantes.

<p align="justify"> 👀
Se pueden sumar las columnas del DataFrame. Por ejemplo:
</p>

In [ ]:
df.Medios = df.Periodico + df.Radio + df.Tv

Crea una nueva columna (o actualiza una existente) llamada "Medios". El valor de cada fila en esta columna se calcula sumando los valores de las columnas "Periodico", "Radio" y "Tv" de esa misma fila. Esta es una operación vectorizada, muy eficiente en Pandas.

In [ ]:
df

   Ventas  Periodico  Radio    Tv  Medios
0   230.1       22.1   37.8  69.2   129.1
1    44.5       10.4   39.3  45.1    94.8
2    17.2        9.3   45.9  69.3   124.5
3   151.5       18.5   41.3  58.5   118.3
4   180.8       12.9   10.8  58.4    82.1

Muestra el DataFrame con la columna "Medios" ahora llena con los resultados de la suma.

In [ ]:
df[["Ventas","Medios","Periodico","Radio","Tv"]] # cambiar el orden de las columnas

   Ventas  Medios  Periodico  Radio    Tv
0   230.1   129.1       22.1   37.8  69.2
1    44.5    94.8       10.4   39.3  45.1
2    17.2   124.5        9.3   45.9  69.3
3   151.5   118.3       18.5   41.3  58.5
4   180.8    82.1       12.9   10.8  58.4

Selecciona un subconjunto de columnas del DataFrame y las reordena. Pasar una lista de nombres de columnas (con doble corchete) devuelve un nuevo DataFrame con esas columnas en el orden especificado.

In [ ]:
df = df[["Ventas","Medios","Periodico","Radio","Tv"]]

In [ ]:
df

   Ventas  Medios  Periodico  Radio    Tv
0   230.1   129.1       22.1   37.8  69.2
1    44.5    94.8       10.4   39.3  45.1
2    17.2   124.5        9.3   45.9  69.3
3   151.5   118.3       18.5   41.3  58.5
4   180.8    82.1       12.9   10.8  58.4

El resultado de la reordenación de columnas de la celda anterior se asigna de nuevo a la variable df, haciendo que el cambio en el orden de las columnas sea permanente.

<p align="justify"> 👀
Podemos hacer transpoción del DataFrame. Por ejemplo:
</p>

In [ ]:
df.T # Transpoción, cambio de lugar filas por columnas

               0     1      2      3      4
Ventas     230.1  44.5   17.2  151.5  180.8
Medios     129.1  94.8  124.5  118.3   82.1
Periodico   22.1  10.4    9.3   18.5   12.9
Radio       37.8  39.3   45.9   41.3   10.8
Tv          69.2  45.1   69.3   58.5   58.4

Utiliza el atributo .T para transponer el DataFrame. Esto intercambia las filas por columnas y viceversa.

<p align="justify">
🟡 Hay que tener en cuenta que la transposición descarta los tipos de datos de columna, si las columnas no tienen todas el mismo tipo de datos, por lo que hacer transposición y hacerla posteriormente de nuevo, puede generar la perdida de información de los datos anteriores. Las columnas se convierten en matrices de objetos puros en este caso.
</p>

 # **<font color="#07a8ed">Selección de Datos </font>**

<p align="justify">
Algunos métodos para la interacción con los datos contenidos en una serie o DataFrame. Para ello, vamos a generar un DataFrame con los valores de la cotización del dolar.</p>

 ## **<font color="#07a8ed">Selección por etiquetas</font>**

<p align="justify">
<code>Pandas</code> proporciona un conjunto de métodos para lograr una indexación. Este es un protocolo estricto basado en la inclusión. En el caso de indexación por etiquetas este es un protocolo estricto basado en la inclusión. Cada etiqueta solicitada debe existir, tanto en el indice como en las columnas. Al seleccionar por ejemplo filas (indice) se incluye el límite inicial indicado y el límite final. <br><br> 👀 Los números enteros son etiquetas válidas, pero se refieren a las etiquetas del indice (cuando la etiqueta es numérica) y no a la posición de cada fila. Lo mismo pasa cuando en el índice tenemos fechas.
</p>

~~~python
df.loc[fila inicial : fila final, columna inicial : columna final]
~~~

In [ ]:
import yfinance as yf

Importa la biblioteca yfinance, una herramienta popular para descargar datos históricos de mercado de Yahoo! Finanzas.

In [ ]:
meli = yf.download("MELI", start="2024-07-01");

/tmp/ipython-input-3888178897.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  meli = yf.download("MELI", start="2024-07-01");
[*********************100%***********************]  1 of 1 completed

Utiliza yfinance para descargar los datos de la acción de MercadoLibre ("MELI") a partir del 1 de julio de 2024 y los almacena en un DataFrame de Pandas llamado meli.

In [ ]:
meli.head()

Price             Close         High          Low         Open  Volume
Ticker             MELI         MELI         MELI         MELI    MELI
Date
2024-07-01  1597.599976  1641.040039  1571.869995  1635.609985  337600
2024-07-02  1596.479980  1617.880005  1583.349976  1590.949951  297400
2024-07-03  1591.439941  1594.119995  1563.209961  1585.000000  207700
2024-07-05  1658.959961  1666.270020  1598.060059  1610.000000  354400
2024-07-08  1683.750000  1700.900024  1647.000000  1659.390015  310500

El método .head() muestra las primeras 5 filas del DataFrame meli, lo que permite una rápida inspección de los datos.

<p align="justify">
Vamos a seleccionar los valores de apertura y de cierre, es decir, las columnas <code>Open</code> y <code>Close</code>.</p>

In [ ]:
meli.loc[:, ["Open", "Close"]] # [fila inicial : fila final , [lista de columnas]]

Price              Open        Close
Ticker             MELI         MELI
Date
2024-07-01  1635.609985  1597.599976
2024-07-02  1590.949951  1596.479980
2024-07-03  1585.000000  1591.439941
2024-07-05  1610.000000  1658.959961
2024-07-08  1659.390015  1683.750000
...                 ...          ...
2025-08-05  2329.110107  2408.020020
2025-08-06  2441.340088  2317.219971
2025-08-07  2338.689941  2334.820068
2025-08-08  2345.469971  2353.699951
2025-08-11  2353.000000  2292.040039

[279 rows x 2 columns]

In [ ]:
meli.loc[:,["Open","Close"]].head()

Price              Open        Close
Ticker             MELI         MELI
Date
2024-07-01  1635.609985  1597.599976
2024-07-02  1590.949951  1596.479980
2024-07-03  1585.000000  1591.439941
2024-07-05  1610.000000  1658.959961
2024-07-08  1659.390015  1683.750000

Demuestran la selección de datos con .loc, que se basa en etiquetas.

- : en la primera posición significa "seleccionar todas las filas".

- ["Open", "Close"] en la segunda posición significa "seleccionar estas columnas específicas por su nombre".

<p align="justify">
O podemos seleccionar también desde el día $01$ de julio al día $06$ de julio.</p>

In [ ]:
meli.loc["2024-07-01":"2024-07-06",:] # [fila inicial : fila final , todas las columnas]

Price             Close         High          Low         Open  Volume
Ticker             MELI         MELI         MELI         MELI    MELI
Date
2024-07-01  1597.599976  1641.040039  1571.869995  1635.609985  337600
2024-07-02  1596.479980  1617.880005  1583.349976  1590.949951  297400
2024-07-03  1591.439941  1594.119995  1563.209961  1585.000000  207700
2024-07-05  1658.959961  1666.270020  1598.060059  1610.000000  354400

Selecciona un rango de filas utilizando las etiquetas del índice (que son fechas). Con .loc, el slicing es inclusivo, por lo que se incluyen tanto la fecha de inicio como la de fin. El : en la segunda posición selecciona todas las columnas.

In [ ]:
meli.loc["2024-07-05":"2024-07-05", ["Open", "Close"]]

Price         Open        Close
Ticker        MELI         MELI
Date
2024-07-05  1610.0  1658.959961

In [ ]:
meli.loc[["2024-07-05"], ["Open", "Close"]]

Price         Open        Close
Ticker        MELI         MELI
Date
2024-07-05  1610.0  1658.959961

Muestran dos formas de seleccionar una única fila por su etiqueta ("2024-07-05") y columnas específicas. Usar una lista [...] permite seleccionar etiquetas no consecutivas (aunque aquí solo hay una).

 ## **<font color="#07a8ed">Selección por posición</font>**

<p align="justify">
<code>Pandas</code> proporciona un conjunto de métodos para obtener una indexación puramente basada en enteros. La semántica sigue de cerca lo definido en <code>Python</code> y <code>NumPy</code>. Al seleccionar, se incluye el límite inicial $n$, mientras que se excluye el límite final $m$, es decir desde $n$ hasta $m-1$ <br><br> 👀 En los parámetros de la selección, siempre se indica primero las filas y luego las columnas. En el caso de seleccionar de un DataFrame, se hace de la siguiente forma:
</p>

~~~python
df.iloc[fila inicial : fila final, columna inicial : columna final]
~~~

<p align="justify">
Vamos a seleccionar los valores de apertura y de cierre, es decir, las columnas <code>Open</code> y <code>Close</code>, pero usando este tipo de selección.</p>

In [ ]:
meli.columns

MultiIndex([( 'Close', 'MELI'),
            (  'High', 'MELI'),
            (   'Low', 'MELI'),
            (  'Open', 'MELI'),
            ('Volume', 'MELI')],
           names=['Price', 'Ticker'])

Muestra el objeto Index que contiene los nombres de todas las columnas del DataFrame.

In [ ]:
meli.iloc[:,[0,3]].head()

Price             Close         Open
Ticker             MELI         MELI
Date
2024-07-01  1597.599976  1635.609985
2024-07-02  1596.479980  1590.949951
2024-07-03  1591.439941  1585.000000
2024-07-05  1658.959961  1610.000000
2024-07-08  1683.750000  1659.390015

Usa .iloc para seleccionar datos por su posición entera.

- : selecciona todas las filas.

- [0,3] selecciona las columnas en la posición 0 ("Open") y 3 ("Close").

<p align="justify">
O podemos seleccionar también desde el día $01$ de julio al día $03$ de julio.</p>

In [ ]:
meli.iloc[0:3,:]

Price             Close         High          Low         Open  Volume
Ticker             MELI         MELI         MELI         MELI    MELI
Date
2024-07-01  1597.599976  1641.040039  1571.869995  1635.609985  337600
2024-07-02  1596.479980  1617.880005  1583.349976  1590.949951  297400
2024-07-03  1591.439941  1594.119995  1563.209961  1585.000000  207700

In [ ]:
meli.iloc[[0],:]

Price             Close         High          Low         Open  Volume
Ticker             MELI         MELI         MELI         MELI    MELI
Date
2024-07-01  1597.599976  1641.040039  1571.869995  1635.609985  337600

<p align="justify">
También podemos seleccionar la posición del dato.</p>

In [ ]:
meli.iloc[0]

Price   Ticker
Close   MELI        1597.599976
High    MELI        1641.040039
Low     MELI        1571.869995
Open    MELI        1635.609985
Volume  MELI      337600.000000
Name: 2024-07-01 00:00:00, dtype: float64

In [ ]:
meli.iloc[[0]]

Price             Close         High          Low         Open  Volume
Ticker             MELI         MELI         MELI         MELI    MELI
Date
2024-07-01  1597.599976  1641.040039  1571.869995  1635.609985  337600

Demuestran la selección de filas con .iloc:

- El slicing 0:3 es exclusivo del final, seleccionando las posiciones 0, 1 y 2.

- Usar [0] (una lista) devuelve un DataFrame, mientras que 0 (un entero) devuelve una Serie.

 ## **<font color="#07a8ed">Filtros</font>**

<p align="justify">
<code>Pandas</code> nos permite llevar a cabo algunas opciones para filtrar nuestros datos, incluidas las máscaras booleanas y algunos métodos especiales. Con las máscaras booleanas, probamos nuestros datos contra algún valor y obtenemos una estructura de la misma forma, excepto que está llena de valores que son <code>True</code> o <code>False</code>.
</p>

In [ ]:
df

   Ventas  Medios  Periodico  Radio    Tv
0   230.1   129.1       22.1   37.8  69.2
1    44.5    94.8       10.4   39.3  45.1
2    17.2   124.5        9.3   45.9  69.3
3   151.5   118.3       18.5   41.3  58.5
4   180.8    82.1       12.9   10.8  58.4

### **<font color="#07a8ed"> Mayor ```>``` Mayor igual ```>=``` Menor ```<``` Menor igual ```<=```</font>**

<p align="justify">
Filtramos los valores Radio mayores a $40$.</p>

In [ ]:
df[df.Radio > 40]

   Ventas  Medios  Periodico  Radio    Tv
2    17.2   124.5        9.3   45.9  69.3
3   151.5   118.3       18.5   41.3  58.5

Demuestran el filtrado por máscara booleana.

- df.Radio > 40 crea una Serie de True/False.

- Al pasar esta Serie dentro de los corchetes df[...], se seleccionan solo las filas del DataFrame df donde la Serie booleana tiene el valor True.

<p align="justify">
Ahora filtramos los valores Radio mayores a $40$, pero con el método <code>query()</code>.</p>

In [ ]:
df.query("Radio > 40")

   Ventas  Medios  Periodico  Radio    Tv
2    17.2   124.5        9.3   45.9  69.3
3   151.5   118.3       18.5   41.3  58.5

Muestra una forma alternativa de filtrar usando el método .query(), que evalúa una condición expresada como una cadena de texto.

### **<font color="#07a8ed">Dos o más condiciones verdaderas ```&```</font>**

<p align="justify">
Para visualizar más de dos condiciones verdaderas, es decir todas las condiciones verdaderas se usa el símbolo &...</p>

In [ ]:
df

   Ventas  Medios  Periodico  Radio    Tv
0   230.1   129.1       22.1   37.8  69.2
1    44.5    94.8       10.4   39.3  45.1
2    17.2   124.5        9.3   45.9  69.3
3   151.5   118.3       18.5   41.3  58.5
4   180.8    82.1       12.9   10.8  58.4

In [ ]:
df[(df.Periodico > 11) & (df.Radio > 41)]

   Ventas  Medios  Periodico  Radio    Tv
3   151.5   118.3       18.5   41.3  58.5

In [ ]:
df.query("Periodico > 11 & Radio > 41")

   Ventas  Medios  Periodico  Radio    Tv
3   151.5   118.3       18.5   41.3  58.5

In [ ]:
df.query("Periodico > 11 and Radio > 41")

   Ventas  Medios  Periodico  Radio    Tv
3   151.5   118.3       18.5   41.3  58.5

Muestran cómo filtrar por múltiples condiciones que deben cumplirse simultáneamente (AND). Para la máscara booleana se usa &, mientras que .query() acepta tanto & como la palabra and.

### **<font color="#07a8ed">Dos o más condiciones, alguna verdadera ```|```</font>**

<p align="justify">
Para visualizar más de dos condiciones y alguna de ellas es verdadera, se usa el símbolo |...</p>

In [ ]:
df

   Ventas  Medios  Periodico  Radio    Tv
0   230.1   129.1       22.1   37.8  69.2
1    44.5    94.8       10.4   39.3  45.1
2    17.2   124.5        9.3   45.9  69.3
3   151.5   118.3       18.5   41.3  58.5
4   180.8    82.1       12.9   10.8  58.4

In [ ]:
df[(df.Periodico > 15) | (df.Radio > 41)]

   Ventas  Medios  Periodico  Radio    Tv
0   230.1   129.1       22.1   37.8  69.2
2    17.2   124.5        9.3   45.9  69.3
3   151.5   118.3       18.5   41.3  58.5

In [ ]:
df.query("Periodico > 15 | Radio > 41")

   Ventas  Medios  Periodico  Radio    Tv
0   230.1   129.1       22.1   37.8  69.2
2    17.2   124.5        9.3   45.9  69.3
3   151.5   118.3       18.5   41.3  58.5

In [ ]:
df.query("Periodico > 15 or Radio > 41")

   Ventas  Medios  Periodico  Radio    Tv
0   230.1   129.1       22.1   37.8  69.2
2    17.2   124.5        9.3   45.9  69.3
3   151.5   118.3       18.5   41.3  58.5

Muestran cómo filtrar por múltiples condiciones donde al menos una debe cumplirse (OR). Para la máscara booleana se usa |, mientras que .query() acepta tanto | como la palabra or.

### **<font color="#07a8ed">Conjunto de valores ```between()```</font>**

<p align="justify">
Para un conjunto de valores entre un intervalo determinado...</p>

In [ ]:
df

   Ventas  Medios  Periodico  Radio    Tv
0   230.1   129.1       22.1   37.8  69.2
1    44.5    94.8       10.4   39.3  45.1
2    17.2   124.5        9.3   45.9  69.3
3   151.5   118.3       18.5   41.3  58.5
4   180.8    82.1       12.9   10.8  58.4

In [ ]:
df[df.Periodico.between(10.4, 22.1)]

   Ventas  Medios  Periodico  Radio    Tv
0   230.1   129.1       22.1   37.8  69.2
1    44.5    94.8       10.4   39.3  45.1
3   151.5   118.3       18.5   41.3  58.5
4   180.8    82.1       12.9   10.8  58.4

In [ ]:
df.query("Periodico >= 10.4 & Periodico <= 22.1")

   Ventas  Medios  Periodico  Radio    Tv
0   230.1   129.1       22.1   37.8  69.2
1    44.5    94.8       10.4   39.3  45.1
3   151.5   118.3       18.5   41.3  58.5
4   180.8    82.1       12.9   10.8  58.4

In [ ]:
df.query("Periodico >= 10.4 and Periodico <= 22.1")

   Ventas  Medios  Periodico  Radio    Tv
0   230.1   129.1       22.1   37.8  69.2
1    44.5    94.8       10.4   39.3  45.1
3   151.5   118.3       18.5   41.3  58.5
4   180.8    82.1       12.9   10.8  58.4

In [ ]:
df[df.Periodico.between(10.4, 22.1, inclusive="neither")] # excluye los extremos

   Ventas  Medios  Periodico  Radio    Tv
3   151.5   118.3       18.5   41.3  58.5
4   180.8    82.1       12.9   10.8  58.4

In [ ]:
df.query("Periodico > 10.4 & Periodico < 22.1") # excluye los extremos

   Ventas  Medios  Periodico  Radio    Tv
3   151.5   118.3       18.5   41.3  58.5
4   180.8    82.1       12.9   10.8  58.4

Demuestran el uso del método .between() para filtrar valores dentro de un rango.

- Por defecto, el rango es inclusivo (incluye los límites).

- El argumento inclusive="neither" hace que el rango sea exclusivo (no incluye los límites).
También se muestra la forma equivalente de hacerlo con .query().

<br>
<br>
<p align="center"><b>
💗
<font color="#07a8ed">
Hemos llegado al final de nuestro colab de Pandas, a seguir codeando...
</font>
</p>