<p align="center">
<img src="https://github.com/cristiandarioortegayubro/BA/blob/main/plotly.png?raw=true">
</p>

 # **<font color="DeepPink">Conociendo Plotly</font>**

<p align="justify">
Plotly es una biblioteca de visualización de datos interactiva que ha experimentado un crecimiento significativo y ha desempeñado un papel importante en el ámbito de Business Data Science.
<br><br>
A continuación un resumen de su historia y evolución, así como su relación con Business Data Science:
<br><br>

1. **Orígenes de Plotly:**
   Plotly fue fundada por Alex Johnson, Chris Parmer y Jack Parmer en 2012. Inicialmente, la empresa se centró en proporcionar una plataforma en la nube para la creación y compartición de gráficos interactivos. Su objetivo era permitir a los usuarios crear visualizaciones de datos dinámicas y colaborativas.

2. **Lanzamiento de Plotly como biblioteca de Python:**
   A medida que Plotly ganaba popularidad, la empresa decidió lanzar una biblioteca de Python en 2015, llamada Plotly.py, que permitía a los usuarios crear gráficos interactivos directamente desde Python. Esta biblioteca se convirtió rápidamente en una opción popular para la visualización de datos en Python, especialmente en el ámbito de la ciencia de datos y el análisis de datos empresariales.

3. **Evolución de Plotly:**
   A lo largo de los años, Plotly ha experimentado una evolución significativa con la introducción de nuevas características y funcionalidades. La empresa ha ampliado su gama de productos para incluir herramientas como Dash, un marco de trabajo para la creación de aplicaciones web interactivas con Python, y Plotly.js, una biblioteca de visualización de datos en JavaScript.

4. **Relevancia en Business Data Science:**
   Plotly se ha convertido en una herramienta importante en el ámbito de Business Data Science por varias razones:
   <br>

   - **Interactividad:** La capacidad de crear visualizaciones de datos interactivas es fundamental para comunicar información de manera efectiva en entornos empresariales. Plotly permite a los profesionales de Business Data Science crear gráficos interactivos que pueden explorarse y analizarse de forma dinámica.

   - **Facilidad de uso:** Plotly ofrece una API sencilla e intuitiva que facilita la creación de una amplia variedad de gráficos y visualizaciones de datos. Esto permite a los usuarios crear visualizaciones de alta calidad con menos esfuerzo y tiempo.

   - **Integración con otras herramientas:** Plotly se integra bien con otras herramientas populares en el ecosistema de Python, como Pandas, NumPy y Jupyter Notebooks. Esto facilita la creación de flujos de trabajo completos para el análisis de datos empresariales utilizando estas herramientas en conjunto.

<br><br>
<p align="justify">
Plotly ha evolucionado desde su fundación en 2012 hasta convertirse en una herramienta esencial de cualquier profesional de Business Data Science.
<br><br>
👀 Su capacidad para crear visualizaciones de datos interactivas y su facilidad de uso lo hacen invaluable para comunicar información y descubrir insights a partir de datos empresariales.

 # **<font color="DeepPink">Usando la Librería Gráfica Plotly</font>**

https://plotly.com/graphing-libraries/

<p align="justify">
La biblioteca gráfica <code>Plotly</code> crea gráficos interactivos con calidad de publicación. Ejemplos de cómo crear gráficos de líneas, diagramas de dispersión, gráficos de área, gráficos de barras, barras de error, diagramas de caja, histogramas, mapas de calor, subgráficos, ejes múltiples, gráficos polares, gráficos de burbujas y todo tipos de gráficos, se desarrollarán a continuación.
</p>

<p align="justify"> 👀 Por convención, así se importa <code>Plotly</code>:  </p>

In [ ]:
import plotly.express as px

 # **<font color="DeepPink">Gráfico lineal</font>**

<p align="justify">
✅ Un gráfico lineal es un tipo de visualización que muestra la relación entre dos conjuntos de datos, generalmente representados en un plano cartesiano con un eje horizontal (eje x) y un eje vertical (eje y). En un gráfico lineal, los puntos de datos se conectan con líneas rectas, lo que permite visualizar la tendencia o la relación entre las variables representadas en los ejes.
<br><br>
Los gráficos lineales son especialmente útiles para mostrar cómo cambia una variable en función de otra, lo que permite identificar tendencias, patrones y relaciones entre los datos.
<br><br>
👀 Por ejemplo, un gráfico lineal puede mostrar cómo cambia la cotización de un activo a lo largo del tiempo, cómo se relaciona el precio de un producto con la demanda, o cómo varía el rendimiento de una inversión en función del tiempo.
<br><br>
Los gráficos lineales son comunes en diversas áreas, incluyendo la ciencia de datos, la economía, las finanzas, la ingeniería y muchas otras disciplinas. Son una herramienta poderosa para la visualización de datos porque permiten una comprensión rápida y clara de las relaciones entre variables y facilitan la comunicación de información importante de manera efectiva.

In [ ]:
import pandas as pd

In [ ]:
# Datos de muestra
df = pd.DataFrame({'x': [1, 2, 3, 4, 5, 6, 7],
                   'y': [10, 15, 25, 18, 43, 30, 65]})

In [ ]:
df

   x   y
0  1  10
1  2  15
2  3  25
3  4  18
4  5  43
5  6  30
6  7  65

In [ ]:
fig = px.line(df,
              x = "x",
              y = "y",
              template = "gridon")

fig.show()

<p align="justify">
El script proporcionado utiliza la biblioteca Plotly Express (abreviada como px) para crear y mostrar un gráfico de línea en un entorno de Google Colab.
<br><br>
A continuación, la explicación del script:
<br><br>

1. **Importación de bibliotecas:** El script importa la biblioteca Plotly Express con el alias `px`. Plotly Express es una interfaz de alto nivel para la creación de gráficos interactivos en Plotly.

2. **Creación del gráfico de línea:** Se utiliza la función `px.line()` para crear un gráfico de línea. Los argumentos de la función especifican el DataFrame `df` que se utilizará para trazar los datos, así como las columnas del DataFrame que se utilizarán para los ejes x e y del gráfico (`x` y `y`, respectivamente). Además, se especifica la plantilla `"gridon"`, que determina el estilo y el diseño del gráfico.

3. **Mostrar el gráfico:** Se utiliza el método `.show()` en el objeto `fig` para mostrar el gráfico en el entorno de Google Colab. Esto genera una visualización interactiva del gráfico de línea creado con Plotly Express.

In [ ]:
fig = px.line(df,
              x = 'x',
              y = 'y',
              template = "gridon",
              title = "Título del gráfico de líneas",
              labels = {'x': 'Eje X', 'y':'Eje Y'})

fig.show()

In [ ]:
fig = px.line(df,
              x = 'x',
              y = 'y',
              template = "gridon",
              markers = True)  ## agrega marcadores en puntos de encuentro de las dos variables

fig.show()

In [ ]:
fig = px.line(df,
              x = 'x',
              y = 'y',
              template = "gridon",
              text = 'y')  ##tome los valores numéricos de la columna 'y' y los escriba explícitamente como etiquetas de texto sobre cada punto del gráfico

fig.update_traces(textposition = "top center") ##ordenando que todas las etiquetas numéricas de los puntos se muevan justo arriba y al centro de cada nodo de la línea.

fig.show()

In [ ]:
fig = px.line(df,
              x = 'x',
              y = 'y',
              template = "gridon",
              markers = True)  ##dibuja una línea continua y lisa sin resaltar los puntos exactos de los datos

fig.update_traces(line = dict(dash = "dot", width = 3, color = "red"),  #Cambia la línea sólida continua por una línea punteada, grosor y color
                  marker = dict(color = "darkblue", size = 15, opacity = 0.8))## marcador,Pinta los nodos o puntos de los quiebres de color azul oscuro,tamaño 15 pixeles, transparencia 20%
##Este método modifica de forma masiva los componentes visuales del trazado. Dentro de él estás configurando dos diccionarios independientes:
fig.show()

In [ ]:
df = pd.DataFrame({'x': [2010, 2011, 2012, 2013, 2010, 2011, 2012, 2013],
                   'y': [10, 15, 25, 18, 43, 30, 6, 12],
                   'grupo': ['G1', 'G1', 'G1', 'G1', 'G2', 'G2', 'G2', 'G2']})

In [ ]:
df

      x   y grupo
0  2010  10    G1
1  2011  15    G1
2  2012  25    G1
3  2013  18    G1
4  2010  43    G2
5  2011  30    G2
6  2012   6    G2
7  2013  12    G2

In [ ]:
fig = px.line(df,
              x = 'x',
              y = 'y',
              template = "gridon",
              color = 'grupo')  ## colores con las categorias de grupo

fig.show()

In [ ]:
fig = px.line(df,
              x = 'x',
              y = 'y',
              template = "gridon",
              color = 'grupo',
              color_discrete_map = {'G1':'green', 'G2':'orange'})  ## asigne colores

fig.show()

In [ ]:
fig = px.line(df,
              x = 'x',
              y = 'y',
              template = "gridon",
              color = 'grupo',
              symbol = 'grupo') ##Modifica la forma geométrica de los marcadores (nodos) para cada serie basándose también en la columna 'grupo'.

fig.show()

In [ ]:
fig = px.line(df,
              x = 'x',
              y = 'y',
              template = "gridon",
              color = 'grupo',
              symbol = 'grupo',
              symbol_map = {'G1': 'square', 'G2': 'cross'})  ## dibuje marcadores segun valor diccionario, cuadrado y cruz

fig.show()

In [ ]:
fig = px.line(df,
              x = 'x',
              y = 'y',
              template = "gridon",
              color = 'grupo',
              line_dash = 'grupo') ##ue asigne automáticamente un tipo de línea distinto (continua, punteada, con guiones, etc.) a cada categoría que encuentre en la columna 'grupo'

fig.show()

In [ ]:
fig = px.line(df,
              x = 'x',
              y = 'y',
              color = 'grupo',
              template = "gridon",
              line_dash = 'grupo',##Cambia la estructura del trazo (sólida, guiones, puntos) para cada categoría.
              line_dash_map = {'G1': 'dashdot', 'G2': 'dash'}) ## asigna tipo linea

fig.show()

<br>
<br>
<p align="center"><b>
💗
<font color="DeepPink">
Hemos llegado al final de nuestro colab, a seguir codeando...
</font>
</p>