# **<font color="#07a8ed">Fundamentos de Python</font>**

<p align="center">
<img src="https://www.python.org/static/community_logos/python-powered-h-70x91.png">
</p>

<p align="justify"><b>
<font color="#07a8ed">
💗 Todo el mundo deberia aprender a programar, porque te enseña a pensar...
</font>
</p>
<p align="right"><b>
<font color="#07a8ed">
Steve Jobs (1995)
</font>
</p>
<br>
<br>

<p align="justify">
Python fue creado por Guido van Rossum y su desarrollo comenzó a finales de los 80 y principios de los 90. Van Rossum buscaba un lenguaje de programación que fuera fácil de leer y entender, y que tuviera una sintaxis clara y concisa. La primera versión pública, Python 0.9.0, fue lanzada en el año 1991.
<br><br>
En relación con el Business Analytics y el Business Data Science, Python ha jugado un papel fundamental en este campo debido a varias razones:
<br><br>

1. **Facilidad de uso y legibilidad:** La sintaxis simple y clara de Python lo hace ideal para analistas y científicos de datos que pueden no tener antecedentes en informática. Esto permite a los profesionales de negocios comprender y utilizar herramientas de análisis de datos sin tener que sumergirse profundamente en la programación.

2. **Amplio ecosistema de bibliotecas:** Python cuenta con una amplia gama de bibliotecas específicamente diseñadas para análisis de datos, como NumPy, Pandas, Plotly, y Scikit-learn, entre otras. Estas bibliotecas proporcionan funcionalidades poderosas para manipular datos, realizar análisis estadísticos y construir modelos predictivos.

3. **Integración con otras tecnologías:** Python se integra bien con otras tecnologías utilizadas, como bases de datos relacionales y no relacionales, herramientas de visualización de datos y plataformas de machine learning.

4. **Comunidad activa:** Python tiene una gran comunidad de usuarios y desarrolladores que contribuyen constantemente con nuevas bibliotecas, tutoriales y recursos. Esto facilita el aprendizaje y la resolución de problemas.

# **<font color="#07a8ed">¿Qué es programación?</font>**

<p align="justify">
La programación es el proceso que se utiliza para diseñar e implementar un programa, valiéndose de algún lenguaje que permita comunicar una serie de acciones que se requiere que la computadora realice. Podemos pensar que es una caja negra que recibe alguna información, la cual es llamada "input" (entrada), realiza alguna acción, y devuelve información, la cual es llamada "output" (salida).</p>

<p align="center">
<img src="https://github.com/cristiandarioortegayubro/BDS/blob/main/images/Image_0004.jpg?raw=true" width="500" height="">
</p>

<p>
<font color="#07a8ed">

**👀 Antes que nada, verificamos la versión de Python con la cual estamos trabajando...**

</font>
</p>

In [ ]:
!python --version

Python 3.11.13

<p align="justify">
El comando <code>!python --version</code> en Google Colab se utiliza para verificar la versión de Python que está instalada en el entorno de ejecución de Colab. Al ejecutar este comando en una celda de código precedido por el signo de exclamación (`!`), se mostrará la versión de Python que está siendo utilizada.
<br><br>
Este comando imprime la información de la versión de Python, y la salida típicamente se ve algo así:
</p>

```
Python 3.x.x
```
<p align="justify">
Donde "3.x.x" es la versión específica de Python que está instalada en ese momento en Google Colab. Es útil para confirmar la versión de Python antes de ejecutar código, ya que algunas bibliotecas y funciones pueden variar entre diferentes versiones de Python.</p>

## **<font color="#07a8ed">Lenguajes de programación</font>**

<p align="justify">
Un lenguaje de programación es un lenguaje formal que proporciona una serie de instrucciones, las cuales permiten a un programador escribir secuencias de órdenes para controlar el comportamiento físico y lógico de una computadora, con el objetivo de que produzca diversas acciones deseadas por el programador y por los usuarios.
<br><br>
Los lenguajes de programación más comunes para Business Analytics y Business Data Science son:
<br><br>

1. **Python:** Python es extremadamente popular debido a su facilidad de uso, su amplio conjunto de bibliotecas especializadas en análisis de datos (como NumPy, Pandas, Plotly, Scikit-learn, entre otras) y su flexibilidad para integrarse con otras tecnologías.

2. **R:** R es otro lenguaje de programación muy utilizado en el ámbito de la ciencia de datos y el análisis estadístico. Tiene una gran variedad de paquetes y bibliotecas específicamente diseñadas para el análisis de datos y la generación de informes, lo que lo hace popular entre los estadísticos y los analistas de datos.

3. **SQL:** Aunque no es un lenguaje de programación en el sentido tradicional, SQL (Structured Query Language) es esencial para trabajar con bases de datos relacionales, que son una fuente común de datos en el ámbito empresarial. Los profesionales de Business Data Science a menudo utilizan SQL para extraer, manipular y analizar datos almacenados en bases de datos.

4. **Julia:** Julia es un lenguaje de programación relativamente nuevo que ha ganado popularidad en el campo de la ciencia de datos debido a su velocidad y capacidad para realizar cálculos numéricos y científicos de manera eficiente. Aunque aún no es tan ampliamente adoptado como Python o R, está ganando terreno rápidamente, especialmente en entornos donde se requiere un rendimiento computacional muy alto.

<br>
<p align="justify">
👀 Estos son algunos de los lenguajes de programación más usuales, pero la elección del lenguaje puede depender de factores como las preferencias personales, los requisitos del proyecto y las herramientas y tecnologías utilizadas en la organización.

## **<font color="#07a8ed">Python: el lenguaje de programación más utilizado en la actualidad</font>**

<p align="justify">
Python es un lenguaje de programación creado por por el informático holandés Guido van Rossum a principios de los años 90 para administrar sistemas operativos, concretamente el sistema operativo Amoeba. Sus construcciones lingüísticas y su enfoque orientado a objetos tienen como objetivo ayudar a los programadores a escribir código claro y lógico para proyectos pequeños y grandes. Python es un lenguaje similar a Perl, pero con una sintaxis muy limpia.<br><br>Python es un lenguaje de tipado dinámico, es decir, que los tipos de datos se asignan a las variables durante su uso, y no durante la escritura o compilación de los programas y de los scripts.
Por eso es muy fácil trabajar con este lenguaje y crear programas flexibles, que se modifiquen sobre la marcha de su ejecución.<br><br> Según el índice TIOBE, el lenguaje más utilziado del mundo en la actualidad es Python. Python ha estado en la cima del índice TIOBE durante los últimos años y ha experimentado un crecimiento significativo en popularidad durante la última década. De hecho, la popularidad de Python se ha triplicado desde 2010, lo que lo convierte en el lenguaje de programación de más rápido crecimiento.
</p>

Python es:
- un lenguaje interpretado o de script,
- con tipado dinámico,
- fuertemente tipado,
- multiplataforma y
- orientado a objetos.

### **<font color="#07a8ed">Lenguaje interpretado o de script</font>**

<p align="justify">
Un lenguaje interpretado o de script es aquel que se ejecuta utilizando un programa intermedio llamado intérprete, en lugar de compilar el código a lenguaje máquina que pueda comprender y ejecutar directamente una computadora (lenguajes compilados).<br><br>
La ventaja de los lenguajes compilados es que su ejecución es más rápida. Sin embargo los lenguajes interpretados son más flexibles y más portables.
Python tiene, no obstante, muchas de las características de los lenguajes compilados, por lo que se podría decir que es semi interpretado.</p>

### **<font color="#07a8ed">Con tipado dinámico</font>**

<p align="justify">
La característica de tipado dinámico se refiere a que no es necesario declarar el tipo de dato que va a contener una determinada variable, sino que su tipo se determinará en tiempo de ejecución según el tipo del valor al que se asigne, y el tipo de esta variable puede cambiar si se le asigna un valor de otro tipo.</p>

### **<font color="#07a8ed">Fuertemente tipado</font>**

<p align="justify">
No se permite tratar a una variable como si fuera de un tipo distinto al que tiene, es necesario convertir de forma explícita dicha variable al nuevo tipo previamente. <br><br>Por ejemplo, si tenemos una variable que contiene un texto (variable de tipo cadena o string) no podremos tratarla como un número (sumar la cadena “9” y el número 8). <br><br>En otros lenguajes el tipo de la variable cambiaría para adaptarse al comportamiento esperado, aunque esto es más propenso a errores.</p>

### **<font color="#07a8ed">Multiplataforma</font>**

<p align="justify">
El intérprete de Python está disponible en multitud de plataformas (UNIX, Solaris, Linux, DOS, Windows, OS/2, Mac OS, etc.) por lo que si no utilizamos librerías específicas de cada plataforma, nuestro programa podrá correr en todos estos sistemas operativos sin grandes cambios.</p>

### **<font color="#07a8ed">Orientado a objetos</font>**

<p align="justify">
La orientación a objetos es un paradigma de programación en el que los conceptos del mundo real relevantes para nuestro problema se trasladan a clases y objetos en nuestro programa. La ejecución del programa consiste en una serie de interacciones entre los objetos.</p>

## **<font color="#07a8ed">Programación orientada a objetos (POO)</font>**

<p align="justify">
Entonces, la programación orientada a objetos es un paradigma de programación que divide los componentes de un programa en objetos. En Python los objetos suelen tener <b>atributos</b> (datos asociados al objeto) y <b>métodos</b> (funciones asociadas con un objeto que pueden tener acceso a los datos internos del objeto). Es decir, el estado del objeto se define a través de variables llamadas atributos, mientras que la funcionalidad se modela a través de funciones a las que se les conoce con el nombre de métodos del objeto.
<br><br>
En Python todo es un <mark>objeto</mark>.
<br><br>
Una característica importante del lenguaje Python es la consistencia de su modelo de objetos. Cada número, cadena de caracteres, estructura de datos (tuplas, listas, diccionarios, conjuntos, etc.), función, clase, módulo, etc. tiene su propia "caja", que se denomina objeto de Python. Por lo general el paradigma orientado a objetos resulta adecuado cuando queremos agrupar estados (datos) y comportamiento (código) juntos en prácticos paquetes de funcionalidad.<br><br>
Los marcos de trabajo y bibliotecas de Python utilizan este paradigma para construir su código base. Algunos ejemplos son Django, Pandas, Scikit-learn, NumPy y TensorFlow.
<br><br>
A continuación, veamos algunos ejemplos de objetos:
</p>

In [ ]:
#número
numero = 20

Esta celda asigna el valor entero 20 a la variable llamada numero.

In [ ]:
numero

20

Al escribir el nombre de la variable numero en la última línea de una celda, Colab muestra automáticamente su valor. En este caso, la salida es 20.

In [ ]:
#cadena de caracteres encerradas en comillas
string = "Python"

Aquí se asigna la cadena de texto "Python" a la variable string.

In [ ]:
string

'Python'

Esta celda muestra el contenido de la variable string, que es 'Python'.

In [ ]:
#tupla
tuple = (1,2,3,4,5)

Se crea una tupla, que es una colección ordenada e inmutable de elementos, y se la asigna a la variable tuple.

In [ ]:
#lista
lista = [1,2,3,4,5]

Se crea una lista, que es una colección ordenada y modificable de elementos, y se la asigna a la variable lista.

In [ ]:
import numpy as np

Esta celda importa la biblioteca NumPy, que es fundamental para la computación numérica en Python. Se le asigna el alias np por convención, para poder referenciarla de forma más corta en el resto del código.

In [ ]:
#lista de 7 números generados aleatoriamente a partir de una distribución normal estándar
list2 = [np.random.standard_normal() for i in range(7)]

Esta línea de código crea una lista llamada list2. Utiliza una "comprensión de listas" para generar 7 números aleatorios que siguen una distribución normal estándar (media 0, desviación estándar 1), utilizando la función standard_normal() de NumPy

In [ ]:
#vector de 3 elementos
array1 = np.array([1,3,5])
print("Vector\n", array1)

#matriz de 2 x 3
array2 = np.array([[1,5,9],[2,6,8]])
print("\nMatriz\n", array2)

Vector
 [1 3 5]

Matriz
 [[1 5 9]
 [2 6 8]]

Este código utiliza NumPy (np) para crear dos estructuras de datos:

- array1: Un arreglo de una dimensión (o vector) con los elementos 1, 3, 5.

- array2: Un arreglo de dos dimensiones (o matriz) con 2 filas y 3 columnas.
Luego, usa la función print() para mostrar ambos arreglos en la salida, junto con un texto descriptivo.

In [ ]:
import pandas as pd

#Dataframe
df1 = pd.DataFrame({"Edad":[30, 40, 50],
                   "Salario": [40000, 38000, 50000]
                   })
df1

   Edad  Salario
0    30    40000
1    40    38000
2    50    50000

1. import pandas as pd: Importa la biblioteca Pandas, esencial para la manipulación y análisis de datos, con el alias pd.

1. df1 = pd.DataFrame(...): Crea un DataFrame (una estructura de datos tabular, similar a una hoja de cálculo) llamado df1. El DataFrame se construye a partir de un diccionario de Python, donde las claves ("Edad", "Salario") se convierten en los nombres de las columnas y los valores (las listas) se convierten en los datos de esas columnas.

1. df1: Muestra el DataFrame resultante.

In [ ]:
import plotly.express as px

Importa la biblioteca Plotly Express bajo el alias px. Plotly Express es una interfaz de alto nivel para crear figuras y gráficos interactivos de forma sencilla.

In [ ]:
px.scatter(df1, x="Edad", y="Salario")

Esta celda utiliza Plotly Express para crear un gráfico de dispersión (scatter plot) interactivo.

- df1: Es el DataFrame que contiene los datos.

- x="Edad": Se asigna la columna "Edad" al eje X.

- y="Salario": Se asigna la columna "Salario" al eje Y.

In [ ]:
df2 = pd.DataFrame(array2, columns=['col_1', 'col_2', 'col_3'])
df2

   col_1  col_2  col_3
0      1      5      9
1      2      6      8

Crea un nuevo DataFrame de Pandas llamado df2 a partir de la matriz de NumPy array2 (creada anteriormente). Se especifican los nombres de las columnas como ['col_1', 'col_2', 'col_3']. Finalmente, muestra el DataFrame.

<p align="justify">
<b>Nota</b>: algunos tipos de objetos de Python son más legibles cuando son impresos usando la función integrada de Python <code>print</code>, otros no. <br><br>Veamos algunos ejemplos: </font>

In [ ]:
list2

[0.3810824082656275,
 0.004077486559243024,
 -0.4104174923651381,
 0.4722712106429052,
 -0.794218391213648,
 -0.35907005226154154,
 -0.08234178897415431]

Muestra el contenido de la variable list2, que contiene los 7 números aleatorios generados previamente.

In [ ]:
print(list2)

[0.3810824082656275, 0.004077486559243024, -0.4104174923651381, 0.4722712106429052, -0.794218391213648, -0.35907005226154154, -0.08234178897415431]

Utiliza la función print() para mostrar la lista list2. La salida es más compacta y en una sola línea en comparación con la celda anterior.

In [ ]:
array2

array([[1, 5, 9],
       [2, 6, 8]])

Muestra el contenido de la matriz array2. La salida de Colab formatea el arreglo para que sea fácil de leer como una matriz.

In [ ]:
print(array2)

[[1 5 9]
 [2 6 8]]

Usa print() para mostrar la matriz array2. La salida es muy similar a la anterior, mostrando la estructura de 2x3.

In [ ]:
df1

   Edad  Salario
0    30    40000
1    40    38000
2    50    50000

Vuelve a mostrar el contenido del DataFrame df1.

In [ ]:
df1.shape

(3, 2)

Accede al atributo shape del DataFrame df1. Este atributo devuelve una tupla que representa las dimensiones del DataFrame: (filas, columnas). La salida (3, 2) indica que tiene 3 filas y 2 columnas.

In [ ]:
print(df1)

   Edad  Salario
0    30    40000
1    40    38000
2    50    50000

Utiliza la función print() para mostrar el DataFrame df1. La salida es un texto plano sin el formato enriquecido de Colab.

## **<font color="#07a8ed">Métodos y atributos</font>**

### **<font color="#07a8ed">Método</font>**

Son las funciones asociadas al objeto. Se accede a los métodos a través de la sintaxis `obj.method_name`.

In [ ]:
string = "python"

Reasigna la variable string con el valor en minúsculas "python".

In [ ]:
nombre = "cristian"

Asigna la cadena de texto "cristian" a la variable nombre.

In [ ]:
nombre.capitalize()

'Cristian'

Llama al método capitalize() en la cadena nombre. Este método devuelve una nueva cadena con el primer carácter en mayúscula y el resto en minúsculas ('Cristian'), pero no modifica la variable original nombre.

In [ ]:
nombre

'cristian'

Muestra el valor actual de la variable nombre, que sigue siendo 'cristian' porque la operación anterior no la modificó.

In [ ]:
nombre = nombre.capitalize()

Llama nuevamente al método capitalize() sobre nombre y esta vez reasigna el resultado a la misma variable nombre. Ahora nombre contendrá el valor 'Cristian'.

In [ ]:
nombre

'Cristian'

Muestra el nuevo valor de nombre, que ahora es 'Cristian'.

In [ ]:
string.upper()

'PYTHON'

Llama al método upper() en la cadena string ("python"). Este método devuelve una nueva cadena con todos sus caracteres en mayúsculas: 'PYTHON'.

In [ ]:
df2.rename(columns={"col_1":"Columna_1",
                    "col_2":"Columns_2",
                    "col_3":"Columna_3"},
           inplace=True)
df2

   Columna_1  Columns_2  Columna_3
0          1          5          9
1          2          6          8

Usa el método rename() para cambiar los nombres de las columnas del DataFrame df2.

- columns={...}: Es un diccionario que mapea los nombres antiguos a los nuevos.

- inplace=True: Este argumento es muy importante; modifica el DataFrame df2 directamente, en lugar de devolver uno nuevo.
Finalmente, se muestra el df2 ya modificado.

### **<font color="#07a8ed">Atributo</font>**

<p align="justify">
Los atributos de datos definen el estado del objeto. En otros lenguajes son conocidos simplemente como atributos.
Son datos asociados al objeto. Se accede a los atributos a través de la sintaxis <code>obj.attribute_name</code>.</p>

In [ ]:
array2

array([[1, 5, 9],
       [2, 6, 8]])

Vuelve a mostrar el contenido de la matriz array2.

In [ ]:
array2.shape

(2, 3)

Accede al atributo shape de la matriz array2, que indica sus dimensiones. La salida (2, 3) confirma que tiene 2 filas y 3 columnas.

In [ ]:
print("La matriz es de ", array2.shape[0], "x", array2.shape[1])

La matriz es de  2 x 3

Imprime una cadena de texto formateada que describe las dimensiones de array2.

- array2.shape[0] obtiene el primer elemento de la tupla shape (el número de filas).

- array2.shape[1] obtiene el segundo elemento (el número de columnas).

## **<font color="#07a8ed">Introspección</font>**

Usando el signo de interrogación (`?`) antes o después de un objeto mostrará su información general.

In [ ]:
?array1

El signo de interrogación ? se usa en Colab/IPython para la introspección. Muestra una ventana de ayuda con información sobre el objeto array1, como su tipo, valor y otros detalles. De nuevo, si array1 no está definida, dará un error.

In [ ]:
df1?

Muestra la ventana de ayuda con la documentación y detalles sobre el objeto DataFrame df1.

Si el objeto es una función, usando `?` también se mostrará la documentación si está definida.

In [ ]:
#función
print?

<p align="justify">
Si creamos una función cualquiera, para agregar esta documentación es necesario abrir y cerrar con tres comillas (simples o dobles). La creación de funciones y clases serán desarrolladas más adelante en este módulo.</p>

In [ ]:
def add_numbers(a, b):
    '''
    Add two numbers together

    Returns
    -------
    the_sum : type of arguments
    '''
    return a + b

Esta celda define una función llamada add_numbers que toma dos argumentos (a y b) y devuelve su suma. El texto entre las tres comillas ''' es el "docstring", que sirve como documentación de la función y es lo que se muestra cuando se usa la introspección (add_numbers?).

## **<font color="#07a8ed">Referencias dinámicas y tipado</font>**

<p align="justify">
Las variables en Python no tienen un tipo inherente asociado con ellas; una variable puede hacer referencia a un tipo diferente de objeto simplemente haciendo una asignación.</p>

In [ ]:
a = 5
type(a)

int

1. Asigna el valor entero 5 a la variable a.

1. La función type() devuelve el tipo del objeto al que apunta la variable a. La salida es int, que significa entero (integer).

In [ ]:
b = "5"
type(b)

str

1. Asigna la cadena de texto "5" a la variable b.

1. type(b) devuelve str, que significa cadena de texto (string).

In [ ]:
c = [1,2,3]
type(c)

list

1. Asigna una lista [1,2,3] a la variable c.

1. type(c) devuelve list, que es el tipo de dato para las listas.

<p align="justify">
Las variables son nombres de objetos, la información de tipo se almacena en el propio objeto.</p>

Realicemos la siguiente operación matemática:

In [ ]:
5 + '5'

TypeError: unsupported operand type(s) for +: 'int' and 'str'

<p align="justify">
!Esta operación genera un error! En algunos lenguajes, la cadena de caracteres <code>'5'</code> puede convertirse implícitamente en un número entero, lo que genera <code>10</code>. En otros, el número entero <code>5</code> puede convertirse en una cadena, lo que genera la cadena concatenada <code>'55'</code>. <br><br>En Python, tales conversiones implícitas no están permitidas. En este sentido decimos que Python es un lenguaje <b>fuertemente tipado</b>, lo que significa que cada objeto tiene un tipo específico.</p>

<p align="justify">
Es importante conocer el tipo de un objeto. También puede verificar que un objeto es una instancia de un tipo particular usando la función <code>isinstance</code>.

In [ ]:
isinstance(a, int)

True

La función isinstance() verifica si un objeto es una instancia de una clase o tipo particular. Aquí, comprueba si la variable a (que contiene el número 5) es de tipo int. Devuelve True porque sí lo es.

<p align="justify">
<code>isinstance</code> puede aceptar una tupla de tipos si desea verificar que el tipo de un objeto se encuentra entre los presentes en la tupla:</p>

In [ ]:
isinstance(a, (int, float))

True

Comprueba si la variable a es una instancia de cualquiera de los tipos dentro de la tupla (int, float). Como a es un int, la condición es verdadera y la celda devuelve True.

<br>
<br>
<p align="center"><b>
💗
<font color="#07a8ed">
Hemos llegado al final de nuestro colab, a seguir codeando...
</font>
</p>