<p align="center">
<img src="https://github.com/cristiandarioortegayubro/BDS/blob/main/images/Logo%20Pandas.png?raw=true">
</p>

 # **<font color="#07a8ed">Empezando a utilizar Pandas 🐼 </font>**

<p align="justify"> 👀 Por convención, así se importa <code>Pandas</code>:  </p>

In [ ]:
import numpy as np
import pandas as pd

Esta celda importa las bibliotecas NumPy y Pandas. Se les asignan los alias estándar np y pd para que sea más corto y fácil referirse a ellas en el resto del código.

<p align="justify"> 👀 Pero como vamos a usar mucho los <code>DataFrame</code> y las <code>Series</code> de <code>Pandas</code>, entonces podemos hacer esto:  </p>

In [ ]:
from pandas import Series, DataFrame

Importa las clases Series y DataFrame directamente del paquete de Pandas. Esto permite crear Series y DataFrames sin tener que escribir pd.Series o pd.DataFrame cada vez, haciendo el código un poco más conciso.

 # **<font color="#07a8ed">Aritmética y alineación de datos</font>**

<p align="justify">
Las estructuras de datos que debemos manejar son: <code>Series</code> y <code>DataFrame</code>. Si bien no son una solución universal para todos los problemas que se pueden plantear, proporcionan una base sólida para una amplia variedad de tareas de datos.</p>

In [ ]:
ventas = pd.Series([230.1, 44.5, 17.2, 151.5, 180.8, 68.90, 144.90], name="Ventas")
periodico = pd.Series([22.1, 10.4, 9.3, 18.5, 12.9], name="Periodico")
radio = pd.Series([37.8, 39.3, 45.9, 41.3, 10.8, 41.9, 36.9], name="Radio")
tv = pd.Series([69.2, 45.1, 69.3, 58.5, 58.4, 52.5], name="Tv")

Crea cuatro objetos Series de Pandas. Cada Serie representa una columna de datos con un nombre específico. Es importante notar que las Series tienen diferentes longitudes.

In [ ]:
ventas

0    230.1
1     44.5
2     17.2
3    151.5
4    180.8
5     68.9
6    144.9
Name: Ventas, dtype: float64

Muestra el contenido de la Serie ventas. La salida muestra el índice a la izquierda (0-6) y los valores a la derecha.

In [ ]:
type(ventas)

pandas.core.series.Series

Utiliza la función type() para verificar el tipo de objeto de la variable ventas, confirmando que es una Serie de Pandas.

In [ ]:
ventas.name # atributo nombre del objeto ventas

'Ventas'

Accede y muestra el atributo .name de la Serie ventas, que es "Ventas".

<p align="justify">
<code>Pandas</code> simplifica el trabajo con objetos que tienen diferentes índices, cuando agregamos objetos, si el índice de uno de esos objetos no es el mismo, el índice resultante será la unión de los pares de índices.<br><br>Por ejemplo:</p>

In [ ]:
print(f"La serie {periodico.name} tiene {len(periodico)} elementos \nLa serie {radio.name} tiene {len(radio)} elementos \nLa serie {tv.name} tiene {len(tv)} elementos")

La serie Periodico tiene 5 elementos
La serie Radio tiene 7 elementos
La serie Tv tiene 6 elementos

Utiliza una f-string para imprimir los nombres y las longitudes (número de elementos) de las otras tres Series, mostrando que tienen tamaños diferentes.

In [ ]:
periodico

0    22.1
1    10.4
2     9.3
3    18.5
4    12.9
Name: Periodico, dtype: float64

In [ ]:
radio

0    37.8
1    39.3
2    45.9
3    41.3
4    10.8
5    41.9
6    36.9
Name: Radio, dtype: float64

In [ ]:
tv

0    69.2
1    45.1
2    69.3
3    58.5
4    58.4
5    52.5
Name: Tv, dtype: float64

Estas celdas muestran el contenido de cada una de las Series periodico, radio y tv.

In [ ]:
multimedia = periodico + radio + tv

Realiza una suma aritmética entre tres Series. Pandas alinea las Series por su índice. Si un índice existe en una serie pero no en otra, el resultado para ese índice será NaN (Not a Number), que representa un valor faltante.

In [ ]:
len(multimedia)

7

Calcula la longitud de la Serie resultante multimedia. La longitud será igual a la del índice más largo de las Series originales.

In [ ]:
multimedia

0    129.1
1     94.8
2    124.5
3    118.3
4     82.1
5      NaN
6      NaN
dtype: float64

Muestra el resultado de la suma. Los índices del 0 al 4 tienen valores numéricos porque esos índices existen en las tres series. Sin embargo, los índices 5 y 6 aparecen como NaN porque no todas las series tienen elementos en esas posiciones.

<p align="justify">
<mark> La alineación de datos internos introduce valores faltantes en las ubicaciones de las etiquetas que no se superponen</mark>, es decir, aquellas series que tienen más elemenos, o elementos que no están en otras series.</p>

<p align="justify"> 👀 En el caso de los <code>DataFrame</code>, la alineación se realiza tanto en filas como en columnas:
</p>

In [ ]:
ventas1 = pd.Series([1200, 4250, 3090, 3400], index=[2019,2020,2022,2023])
costo1 = pd.Series([800, 1900, 1200, 1450], index=[2019,2020,2022,2023])
bruto1 = ventas1 - costo1

Crea tres Series para una "sucursal 1", usando años como índice. bruto1 se calcula restando la Serie costo1 de ventas1. La operación se realiza elemento por elemento para los índices que coinciden.

In [ ]:
ventas2 = pd.Series([4250, 2050, 3400], index=[2020,2021,2023])
costo2 = pd.Series([1900, 1000, 1450], index=[2020,2021,2023])
bruto2 = ventas2 - costo2

Crea tres Series para una "sucursal 2". Nótese que los índices (años) son diferentes a los de la sucursal 1.

In [ ]:
sucursal1 = {"ventas":ventas1,"costo":costo1,"bruto":bruto1}
sucursal2 = {"ventas":ventas2,"costo":costo2,"bruto":bruto2}

Crea dos diccionarios, uno para cada sucursal, donde las claves son nombres de columnas y los valores son las Series correspondientes.

In [ ]:
sucursal1 = pd.DataFrame(sucursal1).T
sucursal2 = pd.DataFrame(sucursal2).T

1. pd.DataFrame(...): Crea un DataFrame para cada sucursal a partir de los diccionarios.

1. .T: Transpone inmediatamente cada DataFrame. Esto hace que las claves del diccionario (ventas, costo, bruto) se conviertan en el índice de las filas y los índices de las Series (los años) se conviertan en las columnas.

In [ ]:
sucursal1

        2019  2020  2022  2023
ventas  1200  4250  3090  3400
costo    800  1900  1200  1450
bruto    400  2350  1890  1950

In [ ]:
sucursal2

        2020  2021  2023
ventas  4250  2050  3400
costo   1900  1000  1450
bruto   2350  1050  1950

Muestran los dos DataFrames de las sucursales. Se puede observar que tienen algunas columnas (años) en común y otras no.

In [ ]:
sucursal1 + sucursal2

        2019  2020  2021  2022  2023
ventas   NaN  8500   NaN   NaN  6800
costo    NaN  3800   NaN   NaN  2900
bruto    NaN  4700   NaN   NaN  3900

Suma los dos DataFrames. Pandas alinea los datos tanto por el índice de filas como por el de columnas. La suma solo se realiza donde ambos DataFrames tienen valores. Para cualquier combinación de fila y columna que no exista en ambos, el resultado es NaN.

<p align="justify"> 👀 Dado que hay columnas (ejercicios comerciales) en las sucursales que no están en ambos objetos <code>DataFrame</code>, aparecen como faltantes en el resultado (sumatoria de las sucursales). <br><br>Lo mismo sucedería para las filas con etiquetas que no son comunes a los objetos que se incluyen en la operación aritmética.
</p>

 # **<font color="#07a8ed">Métodos aritméticos, valores de relleno y operaciones</font>**

<p align="justify"> En las operaciones aritméticas entre objetos indexados de manera diferente, es posible completar valores con un valor especial, como $0$, cuando se encuentra una etiqueta de eje en un objeto pero no en el otro. <br><br>Aquí hay un ejemplo en el que establecemos un valor particular, un valor nulo, usando <code>np.nan</code>:
</p>

In [ ]:
np.random.seed(123)
np.random.rand(12) # muestra de 12 elementos de distribucion uniforme entre 0 y 1

array([0.69646919, 0.28613933, 0.22685145, 0.55131477, 0.71946897,
       0.42310646, 0.9807642 , 0.68482974, 0.4809319 , 0.39211752,
       0.34317802, 0.72904971])

In [ ]:
np.random.seed(123)
np.random.rand(12).reshape((3, 4)) # vector a matriz de 3 filas por 4 columnas

array([[0.69646919, 0.28613933, 0.22685145, 0.55131477],
       [0.71946897, 0.42310646, 0.9807642 , 0.68482974],
       [0.4809319 , 0.39211752, 0.34317802, 0.72904971]])

Estas celdas utilizan NumPy para generar números aleatorios:

- np.random.seed(123): Fija la "semilla" del generador de números aleatorios para que los resultados sean reproducibles.

- np.random.rand(12): Genera un arrays de 12 números aleatorios entre 0 y 1.

- .reshape((3, 4)): Transforma el arrays de 12 elementos en una matriz de 3 filas y 4 columnas.

In [ ]:
np.random.seed(123)
sucursal3 = pd.DataFrame(np.random.rand(12).reshape((3, 4)),columns=[2018,2020,2021,2023])
sucursal4 = pd.DataFrame(np.random.rand(20).reshape((4, 5)),columns=[2019,2020,2021,2022,2023])

Crea dos DataFrames (sucursal3 y sucursal4) con datos aleatorios. Tienen diferentes dimensiones y diferentes nombres de columna.

In [ ]:
sucursal3

       2018      2020      2021      2023
0  0.696469  0.286139  0.226851  0.551315
1  0.719469  0.423106  0.980764  0.684830
2  0.480932  0.392118  0.343178  0.729050

In [ ]:
sucursal4

       2019      2020      2021      2022      2023
0  0.438572  0.059678  0.398044  0.737995  0.182492
1  0.175452  0.531551  0.531828  0.634401  0.849432
2  0.724455  0.611024  0.722443  0.322959  0.361789
3  0.228263  0.293714  0.630976  0.092105  0.433701

Muestran los dos DataFrames con datos aleatorios.

In [ ]:
sucursal3.loc[1, 2020] # un elemento de la sucursal 3

np.float64(0.42310646012446096)

Usa .loc para seleccionar un valor específico del DataFrame sucursal3 basado en su etiqueta de fila (1) y su etiqueta de columna (2020).

In [ ]:
sucursal3.loc[1, 2020] = np.nan # convierto el elemento en valor nulo

Asigna un valor nulo (np.nan) a la celda seleccionada en la fila 1, columna 2020 del DataFrame sucursal3.

In [ ]:
sucursal3

       2018      2020      2021      2023
0  0.696469  0.286139  0.226851  0.551315
1  0.719469       NaN  0.980764  0.684830
2  0.480932  0.392118  0.343178  0.729050

Muestra el DataFrame sucursal3 actualizado, ahora con un valor NaN.

In [ ]:
sucursal3.iloc[:,2]

0    0.226851
1    0.980764
2    0.343178
Name: 2021, dtype: float64

In [ ]:
sucursal3.loc[1, 2021]

np.float64(0.9807641983846155)

In [ ]:
sucursal3[2021].mean()

np.float64(0.516931222699896)

In [ ]:
sucursal3.loc[1, 2021] = sucursal3[2021].mean()

Este bloque de código reemplaza un valor con la media de su columna.

1. La primera celda (no mostrada en la pregunta) muestra la columna en la posición 2.

1. La segunda celda (no mostrada) muestra un valor específico.

1. La tercera celda (no mostrada) calcula la media de la columna 2021.

1. La cuarta celda (no mostrada) asigna el valor de la media de la columna a la celda en la fila 1, columna 2021.

In [ ]:
sucursal3

       2018      2020      2021      2023
0  0.696469  0.286139  0.226851  0.551315
1  0.719469       NaN  0.516931  0.684830
2  0.480932  0.392118  0.343178  0.729050

In [ ]:
sucursal4

       2019      2020      2021      2022      2023
0  0.438572  0.059678  0.398044  0.737995  0.182492
1  0.175452  0.531551  0.531828  0.634401  0.849432
2  0.724455  0.611024  0.722443  0.322959  0.361789
3  0.228263  0.293714  0.630976  0.092105  0.433701

Muestran los DataFrames sucursal3 y sucursal4 para la siguiente operación.

<p align="justify"> 👀 Entonces si sumamos los <code>DataFrame</code>, la alineación se realiza tanto en filas como en columnas, tal cual como vimos anteriormente:
</p>

In [ ]:
sucursal3 + sucursal4

   2018  2019      2020      2021  2022      2023
0   NaN   NaN  0.345817  0.624896   NaN  0.733806
1   NaN   NaN       NaN  1.048759   NaN  1.534262
2   NaN   NaN  1.003141  1.065621   NaN  1.090838
3   NaN   NaN       NaN       NaN   NaN       NaN

Suma los dos DataFrames. Como tienen diferentes tamaños e índices/columnas, el resultado está lleno de valores NaN donde las etiquetas no coinciden en ambos.

 ## **<font color="#07a8ed">Valores de relleno</font>**

<p align="justify"> 👀 Pero si usamos el método <code>add()</code> con el parámetro <code>fill_value</code> entonces el resultado es el siguiente:
</p>

In [ ]:
sucursal3

       2018      2020      2021      2023
0  0.696469  0.286139  0.226851  0.551315
1  0.719469       NaN  0.516931  0.684830
2  0.480932  0.392118  0.343178  0.729050

In [ ]:
sucursal4

       2019      2020      2021      2022      2023
0  0.438572  0.059678  0.398044  0.737995  0.182492
1  0.175452  0.531551  0.531828  0.634401  0.849432
2  0.724455  0.611024  0.722443  0.322959  0.361789
3  0.228263  0.293714  0.630976  0.092105  0.433701

In [ ]:
sucursal3.add(sucursal4)

   2018  2019      2020      2021  2022      2023
0   NaN   NaN  0.345817  0.624896   NaN  0.733806
1   NaN   NaN       NaN  1.048759   NaN  1.534262
2   NaN   NaN  1.003141  1.065621   NaN  1.090838
3   NaN   NaN       NaN       NaN   NaN       NaN

In [ ]:
sucursal3.add(sucursal4, fill_value=0)

       2018      2019      2020      2021      2022      2023
0  0.696469  0.438572  0.345817  0.624896  0.737995  0.733806
1  0.719469  0.175452  0.531551  1.048759  0.634401  1.534262
2  0.480932  0.724455  1.003141  1.065621  0.322959  1.090838
3       NaN  0.228263  0.293714  0.630976  0.092105  0.433701

In [ ]:
sucursal4.add(sucursal3, fill_value=0)

       2018      2019      2020      2021      2022      2023
0  0.696469  0.438572  0.345817  0.624896  0.737995  0.733806
1  0.719469  0.175452  0.531551  1.048759  0.634401  1.534262
2  0.480932  0.724455  1.003141  1.065621  0.322959  1.090838
3       NaN  0.228263  0.293714  0.630976  0.092105  0.433701

- .add() es el método equivalente al operador + para la suma.

- El argumento fill_value=0 es clave: le dice a Pandas que, si un valor falta en cualquiera de los dos DataFrames durante la operación, debe ser tratado como 0 en lugar de NaN. Esto evita que la suma de un número y un valor faltante resulte en NaN.

<p align="justify"> 👀 De otra manera, al volver a indexar una <code>Serie</code> o un <code>DataFrame</code>, también se puede especificar un valor de relleno diferente:
</p>

In [ ]:
sucursal3

       2018      2020      2021      2023
0  0.696469  0.286139  0.226851  0.551315
1  0.719469       NaN  0.516931  0.684830
2  0.480932  0.392118  0.343178  0.729050

In [ ]:
sucursal4

       2019      2020      2021      2022      2023
0  0.438572  0.059678  0.398044  0.737995  0.182492
1  0.175452  0.531551  0.531828  0.634401  0.849432
2  0.724455  0.611024  0.722443  0.322959  0.361789
3  0.228263  0.293714  0.630976  0.092105  0.433701

In [ ]:
sucursal3.reindex(columns=sucursal4.columns, fill_value=0) # no se generan rellenos con cero, porque sucursal4 2020 no tiene nulo

   2019      2020      2021  2022      2023
0     0  0.286139  0.226851     0  0.551315
1     0       NaN  0.516931     0  0.684830
2     0  0.392118  0.343178     0  0.729050

- .add() es el método equivalente al operador + para la suma.

- El argumento fill_value=0 es clave: le dice a Pandas que, si un valor falta en cualquiera de los dos DataFrames durante la operación, debe ser tratado como 0 en lugar de NaN. Esto evita que la suma de un número y un valor faltante resulte en NaN.

In [ ]:
sucursal4.reindex(columns=sucursal3.columns, fill_value=0)

   2018      2020      2021      2023
0     0  0.059678  0.398044  0.182492
1     0  0.531551  0.531828  0.849432
2     0  0.611024  0.722443  0.361789
3     0  0.293714  0.630976  0.433701

Hace lo contrario: conforma sucursal4 a las columnas de sucursal3. Descarta las columnas 2019 y 2022 y añade la columna 2018 rellenándola con ceros.

 ## **<font color="#07a8ed">Otros métodos aritméticos</font>**

<p align="justify"> 👀 Otros métodos aritméticos:
<ul>
<li><code>add()</code> método para la suma</li>
<li><code>sub()</code> método para la resta</li>
<li><code>div()</code> método para dividir</li>
<li><code>mul()</code> método para multiplicar</li>
<li><code>pow()</code> método para potencia</li>
</ul>
</p>

 ## **<font color="#07a8ed">Operaciones entre <code>DataFrame</code> y <code>Series</code></font>**

<p align="justify"> Al igual que con las matrices <code>NumPy</code> de diferentes dimensiones, también se puede hacer operaciones aritméticas entre los <code>DataFrame</code> y las <code>Series</code>.
</p>

<p align="justify"> 👀 Primero vamos a ver el comportamiento en un array de <code>NumPy</code>:
</p>

In [ ]:
array = np.arange(20.).reshape((4, 5))
array

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.]])

In [ ]:
array[0]

array([0., 1., 2., 3., 4.])

In [ ]:
array - array[0]

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 5.,  5.,  5.,  5.,  5.],
       [10., 10., 10., 10., 10.],
       [15., 15., 15., 15., 15.]])

Demuestran la difusión (broadcasting) en NumPy. Cuando se resta un arrays de 1 dimensión (la primera fila) de un arrays de 2 dimensiones, NumPy "extiende" la resta de esa fila a todas las filas del arrays más grande.

<p align="justify"> 👀 Cuando hacemos la operación aritmética de resta, la resta se realiza por cada fila. Esto se conoce como transmisión. Ahora vemos como se comporta la misma operación entre un <code>DataFrame</code> y una <code>Serie</code>.
</p>

In [ ]:
frame = sucursal3
frame

       2018      2020      2021      2023
0  0.696469  0.286139  0.226851  0.551315
1  0.719469       NaN  0.516931  0.684830
2  0.480932  0.392118  0.343178  0.729050

In [ ]:
serie = frame.iloc[0]
serie

2018    0.696469
2020    0.286139
2021    0.226851
2023    0.551315
Name: 0, dtype: float64

In [ ]:
frame - serie

       2018      2020      2021      2023
0  0.000000  0.000000  0.000000  0.000000
1  0.023000       NaN  0.290080  0.133515
2 -0.215537  0.105978  0.116327  0.177735

Demuestran una operación similar entre un DataFrame y una Serie. Pandas alinea el índice de la Serie (serie.index) con las columnas del DataFrame (frame.columns) y realiza la resta fila por fila (broadcasting).

In [ ]:
resultado = (serie - frame).round(2)
resultado

   2018  2020  2021  2023
0  0.00  0.00  0.00  0.00
1 -0.02   NaN -0.29 -0.13
2  0.22 -0.11 -0.12 -0.18

Realiza la operación inversa (Serie - DataFrame) y redondea el resultado a 2 decimales con el método .round().

 # **<font color="#07a8ed">Aplicación y mapeo de funciones</font>**

<p align="justify"> 👀 Las funciones de  <code>NumPy</code> tambien se pueden aplicar en objetos <code>Pandas</code>.
</p>

In [ ]:
resultado

   2018  2020  2021  2023
0  0.00  0.00  0.00  0.00
1 -0.02   NaN -0.29 -0.13
2  0.22 -0.11 -0.12 -0.18

In [ ]:
np.abs(resultado)

   2018  2020  2021  2023
0  0.00  0.00  0.00  0.00
1  0.02   NaN  0.29  0.13
2  0.22  0.11  0.12  0.18

<p align="justify"> 👀 Otra operación frecuente es aplicar una función para arrayss unidimensionales a cada columna o fila de un objeto bidimensional. El método de los <code>DataFrame</code> denominado <code>apply()</code> hace exactamente eso, arrayss unidimensionales.<br><br> Por ejemplo, primero vamos a crear una función que permita calcular la diferencia entre el valor máximo y el valor mínimo de una <code>Serie</code> y esa función la vamos a aplicar con <code>apply()</code>. Lo mismo podriamos hacer con una función <code>lambda</code>, es decir, aplicar una función <code>lambda</code>.
</p>

In [ ]:
frame2 = frame.round(2)
frame2

   2018  2020  2021  2023
0  0.70  0.29  0.23  0.55
1  0.72   NaN  0.52  0.68
2  0.48  0.39  0.34  0.73

1. Crea frame2 redondeando frame.

1. Define una función f1 que calcula el rango (diferencia entre el máximo y el mínimo) de una Serie.

1. Confirma que frame2 es un DataFrame.

In [ ]:
def f1(x):
  return x.max() - x.min()

In [ ]:
type(frame2)

pandas.core.frame.DataFrame

El método .apply() aplica una función a lo largo de un eje del DataFrame. Por defecto (axis=0), aplica la función a cada columna. Ambas celdas calculan el rango para cada columna del frame2, una usando la función f1 predefinida y la otra usando una función lambda equivalente.

In [ ]:
frame2.apply(f1)

2018    0.24
2020    0.10
2021    0.29
2023    0.18
dtype: float64

In [ ]:
frame2.apply(lambda x: x.max() - x.min())

2018    0.24
2020    0.10
2021    0.29
2023    0.18
dtype: float64

In [ ]:
resultado = frame2.apply(lambda x: x.max() - x.min())

In [ ]:
resultado.name = "Diferencia" # cambio el nombre de la serie

Almacena el resultado de la operación .apply() en una nueva Serie llamada resultado, le cambia el nombre a "Diferencia" y confirma que el resultado es una Serie.

In [ ]:
resultado

2018    0.24
2020    0.10
2021    0.29
2023    0.18
Name: Diferencia, dtype: float64

In [ ]:
type(resultado)

pandas.core.series.Series

In [ ]:
frame2

   2018  2020  2021  2023
0  0.70  0.29  0.23  0.55
1  0.72   NaN  0.52  0.68
2  0.48  0.39  0.34  0.73

In [ ]:
frame2.apply(f1, axis="columns")

0    0.47
1    0.20
2    0.39
dtype: float64

In [ ]:
frame2.apply(f1, axis=1)

0    0.47
1    0.20
2    0.39
dtype: float64

Estas celdas demuestran cómo aplicar la función f1 a cada fila en lugar de a cada columna, especificando axis="columns" o axis=1.

In [ ]:
frame2.apply(f1, 1)

0    0.47
1    0.20
2    0.39
dtype: float64

In [ ]:
frame2

   2018  2020  2021  2023
0  0.70  0.29  0.23  0.55
1  0.72   NaN  0.52  0.68
2  0.48  0.39  0.34  0.73

In [ ]:
frame2.apply(lambda x: x.max() - x.min(), axis="columns")

0    0.47
1    0.20
2    0.39
dtype: float64

In [ ]:
frame2.apply(lambda x: x.max() - x.min(), axis=1)

0    0.47
1    0.20
2    0.39
dtype: float64

<p align="justify"> 👀 También se pueden usar funciones de <code>Python</code> basadas en cada uno de los elementos. Supongamos que deseamos aplicar formatos a partir de cada elemento de un <code>DataFrame</code>, es decir, en cada dato.<br><br> Podemos hacer esto con <code>map()</code></p>

In [ ]:
frame

       2018      2020      2021      2023
0  0.696469  0.286139  0.226851  0.551315
1  0.719469       NaN  0.516931  0.684830
2  0.480932  0.392118  0.343178  0.729050

Muestra el DataFrame frame original (sin redondear).

In [ ]:
def f2(x):
  return f"{x:.2f}"

Define una función que formatea un número como una cadena de texto con exactamente dos decimales.

In [ ]:
frame.map(f2)

   2018  2020  2021  2023
0  0.70  0.29  0.23  0.55
1  0.72   nan  0.52  0.68
2  0.48  0.39  0.34  0.73

In [ ]:
frame.map(lambda x: f"{x:.2f}")

   2018  2020  2021  2023
0  0.70  0.29  0.23  0.55
1  0.72   nan  0.52  0.68
2  0.48  0.39  0.34  0.73

El método .map() (conocido como .applymap() en versiones antiguas) aplica una función a cada elemento individualmente en el DataFrame. Ambas celdas aplican la función de formato a cada celda del DataFrame, devolviendo un nuevo DataFrame donde todos los valores son cadenas de texto.

 # **<font color="#07a8ed">Métodos matemáticos y estadísticos</font>**

<p align="justify">
Los objetos de <code>Pandas</code> están equipados con un conjunto de métodos matemáticos y estadísticos. La mayoría de estos métodos entran en la categoría de reducciones, acumulaciones o estadísticas descriptivas, métodos que extraen un valor único (como la suma o la media) de una <code>Serie</code>, o una <code>Serie</code> de valores de las filas o columnas de un <code>DataFrame</code>. <br><br> 👀 En comparación con métodos similares que se encuentran en las matrices <code>NumPy</code>, los métodos de <code>Pandas</code> tienen un manejo integrado para los datos faltantes. </p>

In [ ]:
frame2

   2018  2020  2021  2023
0  0.70  0.29  0.23  0.55
1  0.72   NaN  0.52  0.68
2  0.48  0.39  0.34  0.73

Muestra el DataFrame frame2 para la siguiente operación.

In [ ]:
frame2.shape

(3, 4)

 ## **<font color="#07a8ed">Reducciones</font>**

<p align="justify">
👀 El método <code>sum()</code> devuelve una <code>Serie</code> que contiene la suma de las columnas resultantes de un <code>DataFrame</code>:
</p>

In [ ]:
suma_columna = frame2.sum()
suma_columna.name = "Suma"
suma_columna

2018    1.90
2020    0.68
2021    1.09
2023    1.96
Name: Suma, dtype: float64

In [ ]:
suma_columna.shape # los elementos coinciden con la cantidad de columnas

(4,)

<p align="justify">
👀 Pero si lo que quiero sumar es todo el índice, entonces utilizamos el parametro <code>axis</code>, con el valor <code>columns</code>:
</p>

In [ ]:
frame2

   2018  2020  2021  2023
0  0.70  0.29  0.23  0.55
1  0.72   NaN  0.52  0.68
2  0.48  0.39  0.34  0.73

In [ ]:
suma_indice = frame2.sum(axis="columns")
suma_indice.name = "Suma"
suma_indice

0    1.77
1    1.92
2    1.94
Name: Suma, dtype: float64

In [ ]:
suma_indice.shape # los elementos coinciden con la cantidad de filas

(3,)

 ## **<font color="#07a8ed">Acumulaciones</font>**

<p align="justify">
👀 El método <code>cumsum()</code> devuelve una <code>Serie</code> que contiene la suma acumulada de las columnas resultantes de un <code>DataFrame</code>. Acá tambien se puede utilizar el parámetro <code> axis </code>, con el valor <code>columns</code>.
</p>

In [ ]:
frame2

   2018  2020  2021  2023
0  0.70  0.29  0.23  0.55
1  0.72   NaN  0.52  0.68
2  0.48  0.39  0.34  0.73

In [ ]:
frame2.cumsum()

   2018  2020  2021  2023
0  0.70  0.29  0.23  0.55
1  1.42   NaN  0.75  1.23
2  1.90  0.68  1.09  1.96

In [ ]:
frame2

   2018  2020  2021  2023
0  0.70  0.29  0.23  0.55
1  0.72   NaN  0.52  0.68
2  0.48  0.39  0.34  0.73

In [ ]:
frame2.cumsum(axis="columns")

   2018  2020  2021  2023
0  0.70  0.99  1.22  1.77
1  0.72   NaN  1.24  1.92
2  0.48  0.87  1.21  1.94

 ## **<font color="#07a8ed">Estadisticas descriptivas</font>**

<p align="justify">
👀 Algunos métodos no son reducciones ni acumulaciones. <code>describe()</code> es uno de esos ejemplos. Produce múltiples estadísticas de  una sola vez, expresadas en un resúmen.
</p>

In [ ]:
frame2

   2018  2020  2021  2023
0  0.70  0.29  0.23  0.55
1  0.72   NaN  0.52  0.68
2  0.48  0.39  0.34  0.73

In [ ]:
frame2.describe().round(2)

       2018  2020  2021  2023
count  3.00  2.00  3.00  3.00
mean   0.63  0.34  0.36  0.65
std    0.13  0.07  0.15  0.09
min    0.48  0.29  0.23  0.55
25%    0.59  0.32  0.29  0.62
50%    0.70  0.34  0.34  0.68
75%    0.71  0.36  0.43  0.70
max    0.72  0.39  0.52  0.73

In [ ]:
frame2.describe().T.round(2)

      count  mean   std   min   25%   50%   75%   max
2018    3.0  0.63  0.13  0.48  0.59  0.70  0.71  0.72
2020    2.0  0.34  0.07  0.29  0.32  0.34  0.36  0.39
2021    3.0  0.36  0.15  0.23  0.29  0.34  0.43  0.52
2023    3.0  0.65  0.09  0.55  0.62  0.68  0.70  0.73

El método .describe() calcula un resumen de estadísticas descriptivas (conteo, media, desviación estándar, etc.) para cada columna numérica. La segunda celda añade .T para transponer el resultado, lo que a menudo es más fácil de leer.

 ## **<font color="#07a8ed">Otros métodos matemáticos</font>**

<p align="justify"> 👀 Otros métodos matemáticos y estadísticos, son los siguientes:
<ul>
<li><code>count()</code> número de valores no nulos</li>
<li><code>min()</code> el valor mínimo</li>
<li><code>argmin()</code> ubicaciones de índice (enteros) en las que se obtiene el valor mínimo, no disponible en objetos <code>DataFrame</code></li>
<li><code>argmax()</code> ubicaciones de índice (enteros) en las que se obtiene el valor máximo, no disponible en objetos <code>DataFrame</code></li>
<li><code>idxmin()</code> etiquetas de índice en las que se obtiene el valor mínimo</li>
<li><code>idxmax()</code> etiquetas de índice en las que se obtiene el valor máximo</li>
<li><code>quantile()</code> cuantil de muestra que va de $0$ a $1$ (predeterminado: $0,5$)</li>
<li><code>mean()</code> media de valores</li>
<li><code>median()</code> mediana aritmética ($50$% cuantil) de valores</li>
<li><code>mad()</code> desviación absoluta media del valor medio</li>
<li><code>prod()</code> producto de todos los valores</li>
<li><code>var()</code> varianza de los valores</li>
<li><code>std()</code> desviación estándar de los valores</li>
<li><code>skew()</code> sesgo muestral de los valores</li>
<li><code>kurt()</code> curtosis de los valores</li>
<li><code>diff()</code> diferencia aritmética de los valores</li>
<li><code>pct_change()</code> cambios porcentuales de los valores</li>
</ul>
</p>

 # **<font color="#07a8ed">Correlación y covarianza</font>**

<p align="justify">
Algunas estadísticas de resumen, como la correlación y la covarianza, se calculan a partir de argumentos. </p>

In [ ]:
resultado = sucursal1.T
resultado

      ventas  costo  bruto
2019    1200    800    400
2020    4250   1900   2350
2022    3090   1200   1890
2023    3400   1450   1950

Transpone el DataFrame sucursal1 y lo asigna a una nueva variable resultado.

<p align="justify">
Algunas estadísticas de resumen, como la correlación y la covarianza, se calculan a partir de argumentos. </p>

<p align="justify">
👀 Podemos calcular la correlación con el método <code>corr()</code> entre las ventas y los costos.
</p>

In [ ]:
resultado["ventas"].corr(resultado["costo"]).round(2)

np.float64(0.96)

In [ ]:
resultado.ventas.corr(resultado.costo).round(2)

np.float64(0.96)

Muestran dos formas de calcular la correlación entre dos columnas ("ventas" y "costo"). Se puede acceder a las columnas con la sintaxis de corchetes ["columna"] o, si el nombre no tiene espacios, con la sintaxis de punto .columna.

<p align="justify">
La correlación es una medida estadística que indica la fuerza y la dirección de la relación entre dos variables. Se mide con el coeficiente de correlación, que puede variar entre -1 y 1:
<br><br>

- **1** indica una correlación positiva perfecta: cuando una variable aumenta, la otra también lo hace en proporción directa.
- **-1** indica una correlación negativa perfecta: cuando una variable aumenta, la otra disminuye en proporción directa.
- **0** indica que no hay correlación lineal entre las variables.

<p align="justify">
<br>
En el script <code>resultado["ventas"].corr(resultado["costo"])</code>, se está calculando el coeficiente de correlación entre dos columnas de un DataFrame de pandas: <code>ventas</code> y <code>costo</code>.
<br><br>

- **`resultado["ventas"]`**: Es una serie que representa las ventas en un conjunto de datos.
- **`resultado["costo"]`**: Es una serie que representa los costos en el mismo conjunto de datos.

<p align="justify">
<br>
La función <code>corr()</code> calcula el coeficiente de correlación entre estas dos series. El valor resultante te dirá cómo están relacionadas las ventas y los costos:
<br><br>

- Si el coeficiente es cercano a 1, hay una fuerte relación positiva: a mayor costo, mayores ventas.
- Si el coeficiente es cercano a -1, hay una fuerte relación negativa: a mayor costo, menores ventas.
- Si el coeficiente es cercano a 0, no hay una relación lineal significativa entre ventas y costos.

<p align="justify">
👀 También podemos calcular la covarianza con el método <code>cov()</code> entre las ventas y los costos.
</p>

In [ ]:
resultado["ventas"].cov(resultado["costo"]).round(2)

np.float64(567750.0)

In [ ]:
resultado.ventas.cov(resultado.costo).round(2)

np.float64(567750.0)

De manera similar, calculan la covarianza entre las mismas dos columnas.

<p align="justify">
La <code>covarianza</code> es una medida que indica la dirección de la relación lineal entre dos variables. A diferencia de la correlación, la covarianza no está normalizada y puede tomar cualquier valor, por lo que su interpretación no es tan intuitiva.
<br><br>

- **Covarianza positiva**: Cuando una variable aumenta, la otra también tiende a aumentar. Indica una relación directa entre las dos variables.
- **Covarianza negativa**: Cuando una variable aumenta, la otra tiende a disminuir. Indica una relación inversa entre las dos variables.
- **Covarianza cercana a cero**: Indica que no hay una relación lineal clara entre las variables.

<p align="justify">
<br>
En el script <code>resultado["ventas"].cov(resultado["costo"]).round(2)</code>, se está calculando la covarianza entre dos columnas del DataFrame de pandas: <code>ventas</code> y <code>costo</code>.

- **`resultado["ventas"]`**: Es una serie que representa las ventas en un conjunto de datos.
- **`resultado["costo"]`**: Es una serie que representa los costos en el mismo conjunto de datos.

<p align="justify">
<br>
El valor resultante te dirá cómo varían conjuntamente las ventas y los costos:

- **Valor positivo**: Indica que, en general, cuando los costos aumentan, también lo hacen las ventas, y viceversa.
- **Valor negativo**: Indica que cuando los costos aumentan, las ventas tienden a disminuir, y viceversa.
- **Valor cercano a cero**: Indica que no hay una relación lineal fuerte entre ventas y costos.

<p align="justify">
<br>
La covarianza proporciona una idea de cómo las dos variables cambian juntas, pero a diferencia de la correlación, no indica la fuerza de la relación ni está normalizada.

<p align="justify">
👀 Podemos calcular la correlación en todo el <code>DataFrame</code>. Esto es lo que conocemos como matriz de correlación.
</p>

In [ ]:
resultado.corr()

          ventas     costo     bruto
ventas  1.000000  0.957384  0.987853
costo   0.957384  1.000000  0.900874
bruto   0.987853  0.900874  1.000000

Al llamar al método .corr() en un DataFrame completo, Pandas calcula la matriz de correlación, que muestra la correlación entre cada par de columnas del DataFrame.

<br>
<br>
<p align="center"><b>
💗
<font color="#07a8ed">
Hemos llegado al final de nuestro colab de Pandas, a seguir codeando...
</font>
</p>