<p align="center">
<img src="https://github.com/cristiandarioortegayubro/BA/blob/main/plotly.png?raw=true">
</p>

 # **<font color="DeepPink">Usando plotly, gráficos lineales 📉 </font>**

https://plotly.com/graphing-libraries/

<p align="justify">
La biblioteca gráfica <code>Plotly</code> crea gráficos interactivos con calidad de publicación. Ejemplos de cómo crear gráficos de líneas, diagramas de dispersión, gráficos de área, gráficos de barras, barras de error, diagramas de caja, histogramas, mapas de calor, subgráficos, ejes múltiples, gráficos polares, gráficos de burbujas y todo tipos de gráficos, se desarrollarán a continuación.
</p>

<p align="justify"> 👀 Por convención, así se importa <code>Plotly</code>:  </p>

In [ ]:
import plotly.express as px

<p align="justify">
Para poder graficar, vamos a utilizar un conjunto de datos correspondientes a un Fondo Común de Inversión</p>

In [ ]:
import pandas as pd
import numpy as np
fci = pd.read_csv("https://raw.githubusercontent.com/Viny2030/UMSA-Analisis_de_datos/refs/heads/main/fci.csv")
fci.head()

        Fecha        Concepto  Valor_de_Cuota  Cantidad_de_Cuotas        Monto
0  30/12/2021  Saldo Anterior        9.942921        5.057865e+06  50289952.23
1   24/1/2022         Rescate       10.401265       -4.807108e+05   5000000.00
2   25/1/2022         Rescate       10.408004       -4.803995e+05   5000000.00
3   27/1/2022         Rescate       10.387650       -4.813408e+05   5000000.00
4   31/1/2022         Rescate       10.446154       -4.786451e+05   5000000.00

In [ ]:
fci.to_csv("fci.csv", index=False)

In [ ]:
fci.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Fecha               20 non-null     object
 1   Concepto            20 non-null     object
 2   Valor_de_Cuota      20 non-null     float64
 3   Cantidad_de_Cuotas  20 non-null     float64
 4   Monto               20 non-null     float64
dtypes: float64(3), object(2)
memory usage: 932.0+ bytes

In [ ]:
fci['Fecha'] = pd.to_datetime(fci['Fecha'], dayfirst=True) # de esta forma dejamos año mes dia, sin hora...
fci.head(3)

       Fecha        Concepto  Valor_de_Cuota  Cantidad_de_Cuotas        Monto
0 2021-12-30  Saldo Anterior        9.942921        5.057865e+06  50289952.23
1 2022-01-24         Rescate       10.401265       -4.807108e+05   5000000.00
2 2022-01-25         Rescate       10.408004       -4.803995e+05   5000000.00

In [ ]:
fci.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Fecha               20 non-null     datetime64[ns]
 1   Concepto            20 non-null     object
 2   Valor_de_Cuota      20 non-null     float64
 3   Cantidad_de_Cuotas  20 non-null     float64
 4   Monto               20 non-null     float64
dtypes: datetime64[ns](1), float64(3), object(1)
memory usage: 932.0+ bytes

In [ ]:
fci = fci.round(2)
fci.head()

       Fecha        Concepto  Valor_de_Cuota  Cantidad_de_Cuotas        Monto
0 2021-12-30  Saldo Anterior            9.94          5057865.01  50289952.23
1 2022-01-24         Rescate           10.40          -480710.76   5000000.00
2 2022-01-25         Rescate           10.41          -480399.51   5000000.00
3 2022-01-27         Rescate           10.39          -481340.82   5000000.00
4 2022-01-31         Rescate           10.45          -478645.06   5000000.00

 # **<font color="DeepPink">Desarrollando gráficos lineales</font>**

<p align="justify">
👀 Con <code>px.line()</code> cada punto de datos se representa como coordenadas (cuya ubicación proviene de la columna $x$ y la columna $y$) generando una línea que une esas coordenadas, en un espacio bidimensional.<br><br> Antes de graficar, vemos los datos de un fondo común de inversión, filtrando por los rescates y las suscripciones:</p>

In [ ]:
fci.head(3)

       Fecha        Concepto  Valor_de_Cuota  Cantidad_de_Cuotas        Monto
0 2021-12-30  Saldo Anterior            9.94          5057865.01  50289952.23
1 2022-01-24         Rescate           10.40          -480710.76   5000000.00
2 2022-01-25         Rescate           10.41          -480399.51   5000000.00

In [ ]:
fci.Concepto.unique()

array(['Saldo Anterior', 'Rescate', 'Suscripción'], dtype=object)

In [ ]:
fci.query("Concepto == 'Rescate'").head()

       Fecha Concepto  Valor_de_Cuota  Cantidad_de_Cuotas      Monto
1 2022-01-24  Rescate           10.40          -480710.76  5000000.0
2 2022-01-25  Rescate           10.41          -480399.51  5000000.0
3 2022-01-27  Rescate           10.39          -481340.82  5000000.0
4 2022-01-31  Rescate           10.45          -478645.06  5000000.0
5 2022-02-01  Rescate           10.42          -479656.11  5000000.0

In [ ]:
fci.query("Concepto == 'Suscripción'").head()

        Fecha     Concepto  Valor_de_Cuota  Cantidad_de_Cuotas       Monto
6  2022-02-03  Suscripción           10.49          1792403.45  18800000.0
12 2022-02-24  Suscripción           10.64          2630438.02  28000000.0
14 2022-03-14  Suscripción           11.02          1351703.31  14900000.0
15 2022-03-17  Suscripción           11.13          1338712.38  14900000.0
16 2022-03-21  Suscripción           11.27          1055752.05  11900000.0

<p align="justify">
Entonces los gráficos líneales de <code>Plotly</code> se implementan como diagramas de dispersión conectados, lo que significa que los puntos se trazan y se conectan con líneas en el orden en que se proporcionan, sin reordenación automática.<br><br>Esto hace posible hacer gráficos como el siguiente (el que se encuentra ordenado por fechas), pero también significa que puede ser necesario ordenar explícitamente los datos antes de graficarlos para evitar que las líneas se muevan "hacia atrás" a través del gráfico.
</p>

<p align="justify">
👀 En el siguiente gráfico, usamos algunos parámetros, tales como:</p>

- el dataframe.
- la serie asignada a $x$ (tambien puede ser una lista de series).
- la serie asignada a $y$.
- el título del gráfico.
- el template utilizado.
- los marcadores sobre la línea.
- y los labels (para cambiar los nombres de las etiquetas).

In [ ]:
fig = px.line(fci.query("Concepto =='Rescate'"),
              x=fci.query("Concepto =='Rescate'").Fecha.dt.date,
              y="Valor_de_Cuota",
              title='Fondo Común de Inversión - Rescate',
              template="gridon",
              markers=True,  ##e ordena al gráfico que dibuje un punto físico (marcador) en cada una de las coordenadas exactas de tus datos.
              labels={"Valor_de_Cuota":"Valor de Cuota","x":"Fecha"})
fig.show()

<p align="justify">
👀 En el siguiente gráfico es lo mismo, pero se aplica otro filtro, para visualizar solo las suscripciones. Interesante destacar que se puede colocar dentro del parametro dataframe, un filtro del mismo.</p>

In [ ]:
fig = px.line(fci.query("Concepto =='Suscripción'"),
              x=fci.query("Concepto =='Suscripción'").Fecha.dt.date,
              y="Valor_de_Cuota",
              title='Fondo Común de Inversión - Suscripción',
              template="gridon",
              markers=True,  ##e ordena al gráfico que dibuje un punto físico (marcador) en cada una de las coordenadas exactas de tus datos.
              labels={"Valor_de_Cuota":"Valor de Cuota","x":"Fecha"})
fig.show()

<p align="justify">
👀 En el siguiente gráfico excluye uno de los valores de la serie <code>Concepto</code>, y agrega un parametro denominado <code>color</code>, que incorpora una variable más a nuestro gráfico.</p>

In [ ]:
fci.query("Concepto !='Saldo Anterior'")  ## agrupa excluye Saldo Anterior

        Fecha     Concepto  Valor_de_Cuota  Cantidad_de_Cuotas       Monto
1  2022-01-24      Rescate           10.40          -480710.76   5000000.0
2  2022-01-25      Rescate           10.41          -480399.51   5000000.0
3  2022-01-27      Rescate           10.39          -481340.82   5000000.0
4  2022-01-31      Rescate           10.45          -478645.06   5000000.0
5  2022-02-01      Rescate           10.42          -479656.11   5000000.0
6  2022-02-03  Suscripción           10.49          1792403.45  18800000.0
7  2022-02-07      Rescate           10.55          -474074.88   5000000.0
8  2022-02-09      Rescate           10.53          -759623.94   8000000.0
9  2022-02-16      Rescate           10.60          -565984.18   6000000.0
10 2022-02-17      Rescate           10.59          -283298.85   3000000.0
11 2022-02-23      Rescate           10.63          -470481.56   5000000.0
12 2022-02-24  Suscripción           10.64          2630438.02  28000000.0
13 2022-03-03      Rescate           10.88          -483636.79   5000000.0
14 2022-03-14  Suscripción           11.02          1351703.31  14900000.0
15 2022-03-17  Suscripción           11.13          1338712.38  14900000.0
16 2022-03-21  Suscripción           11.27          1055752.05  11900000.0
17 2022-03-22  Suscripción           11.31           883935.39  10000000.0
18 2022-03-22      Rescate           11.31          -441967.70   5000000.0
19 2022-03-23      Rescate           11.31          -619039.48   7000000.0

In [ ]:
px.line(fci.query("Concepto !='Saldo Anterior'"),
        x=fci.query("Concepto !='Saldo Anterior'").Fecha.dt.date,
        y="Valor_de_Cuota",
        color="Concepto",
        title='Fondo Común de Inversión - Rescate vs. Suscripción',
        template="gridon",
        markers=True,## para activar los puntos o marcadores visuales en cada una de las coordenadas de datos.
        labels={"Valor_de_Cuota":"Valor de Cuota", "x":"Fecha"})

<p align="justify">
👀 Ahora cambiamos el parametro <code>markers</code> por <code>symbol</code>, que agrega sobre la línea, distintos símbolos donde estaban los marcadores.</p>

In [ ]:
px.line(fci.query("Concepto !='Saldo Anterior'"),
        x=fci.query("Concepto !='Saldo Anterior'").Fecha.dt.date,
        y="Valor_de_Cuota",
        color="Concepto",
        hover_name="Concepto",               # titulo de la etiqueta
        title='Fondo Común de Inversión',
        template="gridon",
        symbol="Concepto",
        labels={"Valor_de_Cuota":"Valor de Cuota", "x":"Fecha"})

<p align="justify">
👀 Optimizando un poco mas el gráfico, utilizamos <code>update_traces</code> para colocar sobre la línea, el valor de cada punto. Hay varias posiciones del texto, en este caso, se establece que los valores se ubican por debajo de los puntos de la línea, y a la derecha.</p>

In [ ]:
fig = px.line(fci.query("Concepto =='Suscripción'"),
              x=fci.query("Concepto =='Suscripción'").Fecha.dt.date,
              y="Valor_de_Cuota",
              title='Fondo Común de Inversión',
              template="gridon",
              markers=True,
              labels={"Valor_de_Cuota":"Valor de Cuota","x":"Fecha"},
              text="Valor_de_Cuota")

fig.update_traces(textposition="top left")
##le estás ordenando al gráfico que desplace las etiquetas para que queden alineadas arriba y a la izquierda de cada marcador o elemento visual.
fig.show()

<p align="justify">
👀 Ahora vamos adicionar botones para poder segmentar nuestro gráfico, para ello hacemos un <code>update_xaxes()</code> con el parámetro <code>rangeselector</code> armando una lista para los botones, y cada boton es un diccionario.</p>

In [ ]:
fig = px.line(fci.query("Concepto =='Suscripción'"),
              x=fci.query("Concepto =='Suscripción'").Fecha.dt.date,
              y="Valor_de_Cuota",
              title='Fondo Común de Inversión',
              template="gridon",
              markers=True,
              labels={"Valor_de_Cuota":"Valor de Cuota","x":"Fecha"},
              text="Valor_de_Cuota")

fig.update_traces(textposition="bottom right")

fig.update_xaxes(rangeselector=dict(buttons=list([ ####Modifica las propiedades del eje horizontal (Eje X).
    dict(count=7, label="7 dias", step="day", stepmode="backward"),####Es la cantidad de unidades de tiempo que se van a medir,
    dict(count=14, label="14 dias", step="day", stepmode="backward"),## label etiqueta
    dict(count=1, label="1 mes", step="month", stepmode="backward"), #### Es la unidad de medida de tiempo
    dict(count=2, label="2 meses", step="month", stepmode="backward"), ## Es la dirección del filtro. Significa "hacia atrás" en el tiempo
    dict(label = "Todo el período", step="all")])))

fig.show()

In [ ]:
fci1 = fci.query("Concepto =='Suscripción'")
fci1.head()

        Fecha     Concepto  Valor_de_Cuota  Cantidad_de_Cuotas       Monto
6  2022-02-03  Suscripción           10.49          1792403.45  18800000.0
12 2022-02-24  Suscripción           10.64          2630438.02  28000000.0
14 2022-03-14  Suscripción           11.02          1351703.31  14900000.0
15 2022-03-17  Suscripción           11.13          1338712.38  14900000.0
16 2022-03-21  Suscripción           11.27          1055752.05  11900000.0

In [ ]:
# Gráfico de línea
fig = px.line(fci1,
              x=fci1.Fecha.dt.date,
              y="Valor_de_Cuota",
              title='Fondo Común de Inversión',
              template="gridon",
              markers=True,
              labels={"Valor_de_Cuota": "Valor de Cuota", "x": "Fecha"},
              text="Valor_de_Cuota")

# Línea horizontal para la media del Valor_de_Cuota
fig.add_hline(y=fci1.Valor_de_Cuota.mean(),
              line_color="green",
              line_dash="dot",
              )

# Texto
fig.update_traces(textposition="top left")

# Anotacion Valor medio
fig.update_layout(
    annotations=[
        dict(
            x=fci1.Fecha.dt.date.max(),         # Posición horizontal de la anotación
            y=fci1.Valor_de_Cuota.mean(),       # Posición vertical de la anotación
            xref="x",
            yref="y",
            text="Valor medio",
            showarrow=True,
            arrowhead=2,
            ax=0,
            ay=-25,
            font=dict(size=12, color="green"))])

# Selección de rango de fechas en el eje x
fig.update_xaxes(rangeselector=dict(buttons=list([  ##Modifica las propiedades del eje horizontal (Eje X).
    dict(count=7, label="7 días", step="day", stepmode="backward"),##Es la cantidad de unidades de tiempo que se van a medir,
    dict(count=14, label="14 días", step="day", stepmode="backward"),## label etiqueta
    dict(count=1, label="1 mes", step="month", stepmode="backward"), ## Es la unidad de medida de tiempo
    dict(count=2, label="2 meses", step="month", stepmode="backward"),##Es la dirección del filtro. Significa "hacia atrás" en el tiempo
    dict(label="Todo el período", step="all")
])))

fig.show()

<p align="justify">
👀 Ahora agregamos una línea constante, con la media de los valores de suscripción, para ello utilizamos <code>add_hline</code> que es una linea horizontal.</p>

In [ ]:
# Gráfico de línea
fig = px.line(fci1,
              x=fci1.Fecha.dt.date,
              y="Valor_de_Cuota",
              title='Fondo Común de Inversión',
              template="gridon",
              markers=True,
              labels={"Valor_de_Cuota": "Valor de Cuota", "x": "Fecha"},
              text="Valor_de_Cuota")

# Línea horizontal para la media del Valor_de_Cuota
fig.add_hline(y=fci1.Valor_de_Cuota.mean(),
              line_color="green",
              line_dash="dot",
              )

# Texto
fig.update_traces(textposition="top left")

# Anotacion Valor medio
fig.update_layout(
    annotations=[
        dict(
            x=fci1.Fecha.dt.date.max(),         # Posición horizontal de la anotación
            y=fci1.Valor_de_Cuota.mean(),       # Posición vertical de la anotación
            xref="x",
            yref="y",
            text="Valor medio",
            showarrow=True,
            arrowhead=2,
            ax=0,
            ay=-25,
            font=dict(size=12, color="green"))])

# Selección de rango de fechas en el eje x
fig.update_xaxes(rangeselector=dict(buttons=list([  ##Modifica las propiedades del eje horizontal (Eje X).
    dict(count=7, label="7 días", step="day", stepmode="backward"),##Es la cantidad de unidades de tiempo que se van a medir,
    dict(count=14, label="14 días", step="day", stepmode="backward"),## label etiqueta
    dict(count=1, label="1 mes", step="month", stepmode="backward"), ## Es la unidad de medida de tiempo
    dict(count=2, label="2 meses", step="month", stepmode="backward"),##Es la dirección del filtro. Significa "hacia atrás" en el tiempo
    dict(label="Todo el período", step="all")
])))

fig.show()

<p align="justify">
👀 Y verificamos el valor de la media, calculando con <code>mean()</code> para ver si la linea que adicionamos esta bien posicionada, y vemos que si.<br><br>El truco en este último grafico fue filtrar por fuera del gráfico, asignar el resultante de ese filtrado a un objeto, y trabajar con ese objeto en el script del gráfico</p>

In [ ]:
fci1.Valor_de_Cuota.mean().round(2)

np.float64(10.98)

<br>
<br>
<p align="center"><b>
💗
<font color="DeepPink">
Hemos llegado al final de nuestro colab, a seguir codeando...
</font>
</p>