## **Análisis Exploratorio de los Datos**

**En este cuaderno colab se realizaran algunas tareas de preprocesamiento de los datos...**

## **Actualizando los módulos necesarios**

In [1]:
!pip install scikit-learn --upgrade

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Collecting scikit-learn
  Downloading scikit_learn-1.9.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.10.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.21.2)
Requirement already satisfied: threadpoolctl>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Downloading scikit_learn-1.9.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (9.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 70.1 MB/s eta 0:00:00
Installing collected packages: scikit-learn
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.6.1
    Uninstalling scikit-learn-1.6.1:
      Successfully uninstalled scikit-learn-1.6.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sklearn-compat 0.1.5 requires scikit-learn<1.9,>=1.2, but you have scikit-learn 1.9.0 which is incompatible.
Successfully installed scikit-learn-1.9.0

## **Carga de módulos**

### **Para análisis de los datos**

In [2]:
import pandas as pd
import numpy as np

### **Para preprocesamiento de los datos**

In [27]:
from sklearn.preprocessing import LabelEncoder

In [28]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import RobustScaler

## **Carga de Datos**

In [ ]:
url = "https://raw.githubusercontent.com/Viny2030/UMSA-Analisis_de_datos/refs/heads/main/visualizacion.csv"

In [ ]:
analisis = pd.read_csv(url)
analisis.head()

,Unnamed: 0,niveldesatisfaccion,ultimaevaluacion,numerosdeproyectos,horasmensualespromedio,tiempoenlaempresa,accidentedetrabajo,abandono,promocionultimos5años,ventas,sueldo
0,0,0.38,0.53,2,157,3,0,1,0,sales,low
1,1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,2,0.11,0.88,7,272,4,0,1,0,sales,medium
3,3,0.72,0.87,5,223,5,0,1,0,sales,low
4,4,0.37,0.52,2,159,3,0,1,0,sales,low

In [ ]:
analisis.to_csv("visualizacion.csv", index=False)

**Se cambian los nombres de las columnas para mejor interpretacion...**

In [ ]:
analisis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              14999 non-null  int64
 1   niveldesatisfaccion     14999 non-null  float64
 2   ultimaevaluacion        14999 non-null  float64
 3   numerosdeproyectos      14999 non-null  int64
 4   horasmensualespromedio  14999 non-null  int64
 5   tiempoenlaempresa       14999 non-null  int64
 6   accidentedetrabajo      14999 non-null  int64
 7   abandono                14999 non-null  int64
 8   promocionultimos5años   14999 non-null  int64
 9   ventas                  14999 non-null  object
 10  sueldo                  14999 non-null  object
dtypes: float64(2), int64(7), object(2)
memory usage: 1.3+ MB

In [ ]:
analisis.rename(columns={"satisfaction_level":"niveldesatisfaccion",
                         "last_evaluation":"ultimaevaluacion",
                         "number_project":"numerosdeproyectos",
                         "average_montly_hours":"horasmensualespromedio",
                         "time_spend_company":"tiempoenlaempresa",
                         "Work_accident":"accidentedetrabajo",
                         "left":"abandono",
                         "promotion_last_5years":"promocionultimos5años",
                         "sales":"ventas",
                         "salary":"sueldo"}, inplace= True)

In [ ]:
analisis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   niveldesatisfaccion     14999 non-null  float64
 1   ultimaevaluacion        14999 non-null  float64
 2   numerosdeproyectos      14999 non-null  int64
 3   horasmensualespromedio  14999 non-null  int64
 4   tiempoenlaempresa       14999 non-null  int64
 5   accidentedetrabajo      14999 non-null  int64
 6   abandono                14999 non-null  int64
 7   promocionultimos5años   14999 non-null  int64
 8   ventas                  14999 non-null  object
 9   sueldo                  14999 non-null  object
dtypes: float64(2), int64(6), object(2)
memory usage: 1.1+ MB

# **Limpieza y transformación de los datos**

## **Filtrado de datos**

In [ ]:
analisis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   niveldesatisfaccion     14999 non-null  float64
 1   ultimaevaluacion        14999 non-null  float64
 2   numerosdeproyectos      14999 non-null  int64
 3   horasmensualespromedio  14999 non-null  int64
 4   tiempoenlaempresa       14999 non-null  int64
 5   accidentedetrabajo      14999 non-null  int64
 6   abandono                14999 non-null  int64
 7   promocionultimos5años   14999 non-null  int64
 8   ventas                  14999 non-null  object
 9   sueldo                  14999 non-null  object
dtypes: float64(2), int64(6), object(2)
memory usage: 1.1+ MB

In [ ]:
analisis.head(2)

,niveldesatisfaccion,ultimaevaluacion,numerosdeproyectos,horasmensualespromedio,tiempoenlaempresa,accidentedetrabajo,abandono,promocionultimos5años,ventas,sueldo
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium

In [ ]:
analisis.rename(columns={"ventas":"sector"}, inplace=True)

In [ ]:
analisis.filter(["sector", "sueldo"])

        sector  sueldo
0        sales     low
1        sales  medium
2        sales  medium
3        sales     low
4        sales     low
...        ...     ...
14994  support     low
14995  support     low
14996  support     low
14997  support     low
14998  support     low

[14999 rows x 2 columns]

In [ ]:
analisis.sueldo

0           low
1        medium
2        medium
3           low
4           low
          ...
14994       low
14995       low
14996       low
14997       low
14998       low
Name: sueldo, Length: 14999, dtype: object

In [ ]:
analisis.filter([0,1,2,5,7,19],axis=0)

,niveldesatisfaccion,ultimaevaluacion,numerosdeproyectos,horasmensualespromedio,tiempoenlaempresa,accidentedetrabajo,abandono,promocionultimos5años,sector,sueldo
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.11,0.88,7,272,4,0,1,0,sales,medium
5,0.41,0.50,2,153,3,0,1,0,sales,low
7,0.92,0.85,5,259,5,0,1,0,sales,low
19,0.76,0.89,5,262,5,0,1,0,sales,low

In [ ]:
analisis[analisis.sector=="support"]

,niveldesatisfaccion,ultimaevaluacion,numerosdeproyectos,horasmensualespromedio,tiempoenlaempresa,accidentedetrabajo,abandono,promocionultimos5años,sector,sueldo
46,0.40,0.55,2,147,3,0,1,0,support,low
47,0.57,0.70,3,273,6,0,1,0,support,low
48,0.40,0.54,2,148,3,0,1,0,support,low
49,0.43,0.47,2,147,3,0,1,0,support,low
50,0.13,0.78,6,152,2,0,1,0,support,low
...,...,...,...,...,...,...,...,...,...,...
14994,0.40,0.57,2,151,3,0,1,0,support,low
14995,0.37,0.48,2,160,3,0,1,0,support,low
14996,0.37,0.53,2,143,3,0,1,0,support,low
14997,0.11,0.96,6,280,4,0,1,0,support,low
14998,0.37,0.52,2,158,3,0,1,0,support,low

## **Valores faltantes**

In [7]:
url2 = "https://raw.githubusercontent.com/Viny2030/UMSA-Analisis_de_datos/refs/heads/main/empleados.csv"

In [8]:
empleados = pd.read_csv(url2)

In [9]:
empleados

             nombre  edad   sueldo sexo      sector nivel  performance
0        Alan Smith  45.0      NaN  NaN  Operations    G3          723
1      Sandro Kumar   NaN  16000.0    F     Finance    G0          520
2    Jacinto Morgan  32.0  35000.0    M     Finance    G2          674
3      Ernesto Chin  45.0  65000.0    F       Sales    G3          556
4    Fernanda Patel  30.0  42000.0    F  Operations    G2          711
5     Samara Sharma   NaN  62000.0  NaN       Sales    G3          649
6   Joaquin Fleiman  54.0      NaN    F  Operations    G3           53
7      Juana Wilkis  54.0  52000.0    F     Finance    G3          901
8  Leonardo Doberti  23.0  98000.0    M       Sales    G4          709

In [6]:
empleados.to_csv("empleados.csv", index=False)

### **Eliminando los NaN**

In [10]:
empleados.dropna(how="any", inplace=True)

In [11]:
empleados

             nombre  edad   sueldo sexo      sector nivel  performance
2    Jacinto Morgan  32.0  35000.0    M     Finance    G2          674
3      Ernesto Chin  45.0  65000.0    F       Sales    G3          556
4    Fernanda Patel  30.0  42000.0    F  Operations    G2          711
7      Juana Wilkis  54.0  52000.0    F     Finance    G3          901
8  Leonardo Doberti  23.0  98000.0    M       Sales    G4          709

### **Completando los NaN**

In [12]:
empleados = pd.read_csv(url2)
empleados

             nombre  edad   sueldo sexo      sector nivel  performance
0        Alan Smith  45.0      NaN  NaN  Operations    G3          723
1      Sandro Kumar   NaN  16000.0    F     Finance    G0          520
2    Jacinto Morgan  32.0  35000.0    M     Finance    G2          674
3      Ernesto Chin  45.0  65000.0    F       Sales    G3          556
4    Fernanda Patel  30.0  42000.0    F  Operations    G2          711
5     Samara Sharma   NaN  62000.0  NaN       Sales    G3          649
6   Joaquin Fleiman  54.0      NaN    F  Operations    G3           53
7      Juana Wilkis  54.0  52000.0    F     Finance    G3          901
8  Leonardo Doberti  23.0  98000.0    M       Sales    G4          709

In [13]:
empleados["edad"] = empleados.edad.fillna(empleados.edad.mean())
empleados

             nombre       edad   sueldo sexo      sector nivel  performance
0        Alan Smith  45.000000      NaN  NaN  Operations    G3          723
1      Sandro Kumar  40.428571  16000.0    F     Finance    G0          520
2    Jacinto Morgan  32.000000  35000.0    M     Finance    G2          674
3      Ernesto Chin  45.000000  65000.0    F       Sales    G3          556
4    Fernanda Patel  30.000000  42000.0    F  Operations    G2          711
5     Samara Sharma  40.428571  62000.0  NaN       Sales    G3          649
6   Joaquin Fleiman  54.000000      NaN    F  Operations    G3           53
7      Juana Wilkis  54.000000  52000.0    F     Finance    G3          901
8  Leonardo Doberti  23.000000  98000.0    M       Sales    G4          709

In [14]:
empleados = pd.read_csv(url2)
empleados["edad"] = round(empleados.edad.fillna(empleados.edad.mean()),0)
empleados

             nombre  edad   sueldo sexo      sector nivel  performance
0        Alan Smith  45.0      NaN  NaN  Operations    G3          723
1      Sandro Kumar  40.0  16000.0    F     Finance    G0          520
2    Jacinto Morgan  32.0  35000.0    M     Finance    G2          674
3      Ernesto Chin  45.0  65000.0    F       Sales    G3          556
4    Fernanda Patel  30.0  42000.0    F  Operations    G2          711
5     Samara Sharma  40.0  62000.0  NaN       Sales    G3          649
6   Joaquin Fleiman  54.0      NaN    F  Operations    G3           53
7      Juana Wilkis  54.0  52000.0    F     Finance    G3          901
8  Leonardo Doberti  23.0  98000.0    M       Sales    G4          709

In [15]:
empleados = pd.read_csv(url2)
empleados["edad"] = empleados.edad.fillna(empleados.edad.median())
empleados

             nombre  edad   sueldo sexo      sector nivel  performance
0        Alan Smith  45.0      NaN  NaN  Operations    G3          723
1      Sandro Kumar  45.0  16000.0    F     Finance    G0          520
2    Jacinto Morgan  32.0  35000.0    M     Finance    G2          674
3      Ernesto Chin  45.0  65000.0    F       Sales    G3          556
4    Fernanda Patel  30.0  42000.0    F  Operations    G2          711
5     Samara Sharma  45.0  62000.0  NaN       Sales    G3          649
6   Joaquin Fleiman  54.0      NaN    F  Operations    G3           53
7      Juana Wilkis  54.0  52000.0    F     Finance    G3          901
8  Leonardo Doberti  23.0  98000.0    M       Sales    G4          709

In [16]:
empleados["sueldo"] = empleados.sueldo.fillna(empleados.sueldo.median())
empleados

             nombre  edad   sueldo sexo      sector nivel  performance
0        Alan Smith  45.0  52000.0  NaN  Operations    G3          723
1      Sandro Kumar  45.0  16000.0    F     Finance    G0          520
2    Jacinto Morgan  32.0  35000.0    M     Finance    G2          674
3      Ernesto Chin  45.0  65000.0    F       Sales    G3          556
4    Fernanda Patel  30.0  42000.0    F  Operations    G2          711
5     Samara Sharma  45.0  62000.0  NaN       Sales    G3          649
6   Joaquin Fleiman  54.0  52000.0    F  Operations    G3           53
7      Juana Wilkis  54.0  52000.0    F     Finance    G3          901
8  Leonardo Doberti  23.0  98000.0    M       Sales    G4          709

## **Codificación**

In [17]:
empleados = pd.read_csv(url2)
empleados.dropna(how="any", inplace=True)
empleados.reset_index(drop=True, inplace=True)
empleados

             nombre  edad   sueldo sexo      sector nivel  performance
0    Jacinto Morgan  32.0  35000.0    M     Finance    G2          674
1      Ernesto Chin  45.0  65000.0    F       Sales    G3          556
2    Fernanda Patel  30.0  42000.0    F  Operations    G2          711
3      Juana Wilkis  54.0  52000.0    F     Finance    G3          901
4  Leonardo Doberti  23.0  98000.0    M       Sales    G4          709

In [18]:
empleadoscodificados = pd.get_dummies(empleados["sexo"])

In [19]:
empleadoscodificados

       F      M
0  False   True
1   True  False
2   True  False
3   True  False
4  False   True

In [20]:
empleados = empleados.join(empleadoscodificados)

In [21]:
empleados

,nombre,edad,sueldo,sexo,sector,nivel,performance,F,M
0,Jacinto Morgan,32.0,35000.0,M,Finance,G2,674,False,True
1,Ernesto Chin,45.0,65000.0,F,Sales,G3,556,True,False
2,Fernanda Patel,30.0,42000.0,F,Operations,G2,711,True,False
3,Juana Wilkis,54.0,52000.0,F,Finance,G3,901,True,False
4,Leonardo Doberti,23.0,98000.0,M,Sales,G4,709,False,True

**O todo en una sola linea... primero cargamos el dataframe**

In [22]:
empleados = pd.read_csv(url2)
empleados.dropna(how="any", inplace=True)
empleados.reset_index(drop=True, inplace=True)
empleados

             nombre  edad   sueldo sexo      sector nivel  performance
0    Jacinto Morgan  32.0  35000.0    M     Finance    G2          674
1      Ernesto Chin  45.0  65000.0    F       Sales    G3          556
2    Fernanda Patel  30.0  42000.0    F  Operations    G2          711
3      Juana Wilkis  54.0  52000.0    F     Finance    G3          901
4  Leonardo Doberti  23.0  98000.0    M       Sales    G4          709

**Ahora si, una linea**

In [23]:
empleados = empleados.join(pd.get_dummies(empleados["sexo"]))

In [24]:
empleados

,nombre,edad,sueldo,sexo,sector,nivel,performance,F,M
0,Jacinto Morgan,32.0,35000.0,M,Finance,G2,674,False,True
1,Ernesto Chin,45.0,65000.0,F,Sales,G3,556,True,False
2,Fernanda Patel,30.0,42000.0,F,Operations,G2,711,True,False
3,Juana Wilkis,54.0,52000.0,F,Finance,G3,901,True,False
4,Leonardo Doberti,23.0,98000.0,M,Sales,G4,709,False,True

In [25]:
empleados = pd.read_csv(url2)
empleados

             nombre  edad   sueldo sexo      sector nivel  performance
0        Alan Smith  45.0      NaN  NaN  Operations    G3          723
1      Sandro Kumar   NaN  16000.0    F     Finance    G0          520
2    Jacinto Morgan  32.0  35000.0    M     Finance    G2          674
3      Ernesto Chin  45.0  65000.0    F       Sales    G3          556
4    Fernanda Patel  30.0  42000.0    F  Operations    G2          711
5     Samara Sharma   NaN  62000.0  NaN       Sales    G3          649
6   Joaquin Fleiman  54.0      NaN    F  Operations    G3           53
7      Juana Wilkis  54.0  52000.0    F     Finance    G3          901
8  Leonardo Doberti  23.0  98000.0    M       Sales    G4          709

In [29]:
etiqueta_ordenada = LabelEncoder()

In [30]:
empleados["nivel_cod"] = etiqueta_ordenada.fit_transform(empleados["nivel"])

In [31]:
empleados

,nombre,edad,sueldo,sexo,sector,nivel,performance,nivel_cod
0,Alan Smith,45.0,NaN,NaN,Operations,G3,723,2
1,Sandro Kumar,NaN,16000.0,F,Finance,G0,520,0
2,Jacinto Morgan,32.0,35000.0,M,Finance,G2,674,1
3,Ernesto Chin,45.0,65000.0,F,Sales,G3,556,2
4,Fernanda Patel,30.0,42000.0,F,Operations,G2,711,1
5,Samara Sharma,NaN,62000.0,NaN,Sales,G3,649,2
6,Joaquin Fleiman,54.0,NaN,F,Operations,G3,53,2
7,Juana Wilkis,54.0,52000.0,F,Finance,G3,901,2
8,Leonardo Doberti,23.0,98000.0,M,Sales,G4,709,3

## **Escalas de las características de los datos**

In [32]:
escala = StandardScaler()

In [33]:
escala.fit(empleados["performance"].values.reshape(-1,1))

StandardScaler()

In [34]:
empleados["escala_perform"]=escala.transform(empleados["performance"].values.reshape(-1,1))

In [35]:
empleados

,nombre,edad,sueldo,sexo,sector,nivel,performance,nivel_cod,escala_perform
0,Alan Smith,45.0,NaN,NaN,Operations,G3,723,2,0.505565
1,Sandro Kumar,NaN,16000.0,F,Finance,G0,520,0,-0.408053
2,Jacinto Morgan,32.0,35000.0,M,Finance,G2,674,1,0.285037
3,Ernesto Chin,45.0,65000.0,F,Sales,G3,556,2,-0.246032
4,Fernanda Patel,30.0,42000.0,F,Operations,G2,711,1,0.451558
5,Samara Sharma,NaN,62000.0,NaN,Sales,G3,649,2,0.172522
6,Joaquin Fleiman,54.0,NaN,F,Operations,G3,53,2,-2.509823
7,Juana Wilkis,54.0,52000.0,F,Finance,G3,901,2,1.306668
8,Leonardo Doberti,23.0,98000.0,M,Sales,G4,709,3,0.442557

In [36]:
escalaminmax = MinMaxScaler()

In [37]:
escalaminmax.fit(empleados["performance"].values.reshape(-1,1))

MinMaxScaler()

In [38]:
empleados["escala_minmax"]=escalaminmax.transform(empleados["performance"].values.reshape(-1,1))

In [39]:
empleados

,nombre,edad,sueldo,sexo,sector,nivel,performance,nivel_cod,escala_perform,escala_minmax
0,Alan Smith,45.0,NaN,NaN,Operations,G3,723,2,0.505565,0.790094
1,Sandro Kumar,NaN,16000.0,F,Finance,G0,520,0,-0.408053,0.550708
2,Jacinto Morgan,32.0,35000.0,M,Finance,G2,674,1,0.285037,0.732311
3,Ernesto Chin,45.0,65000.0,F,Sales,G3,556,2,-0.246032,0.593160
4,Fernanda Patel,30.0,42000.0,F,Operations,G2,711,1,0.451558,0.775943
5,Samara Sharma,NaN,62000.0,NaN,Sales,G3,649,2,0.172522,0.702830
6,Joaquin Fleiman,54.0,NaN,F,Operations,G3,53,2,-2.509823,0.000000
7,Juana Wilkis,54.0,52000.0,F,Finance,G3,901,2,1.306668,1.000000
8,Leonardo Doberti,23.0,98000.0,M,Sales,G4,709,3,0.442557,0.773585

In [40]:
escala_robusta = RobustScaler()

In [41]:
escala_robusta.fit(empleados["performance"].values.reshape(-1,1))

RobustScaler()

In [42]:
empleados["escala_robusta"]=escala_robusta.transform(empleados["performance"].values.reshape(-1,1))

In [43]:
empleados

,nombre,edad,sueldo,sexo,sector,nivel,performance,nivel_cod,escala_perform,escala_minmax,escala_robusta
0,Alan Smith,45.0,NaN,NaN,Operations,G3,723,2,0.505565,0.790094,0.316129
1,Sandro Kumar,NaN,16000.0,F,Finance,G0,520,0,-0.408053,0.550708,-0.993548
2,Jacinto Morgan,32.0,35000.0,M,Finance,G2,674,1,0.285037,0.732311,0.000000
3,Ernesto Chin,45.0,65000.0,F,Sales,G3,556,2,-0.246032,0.593160,-0.761290
4,Fernanda Patel,30.0,42000.0,F,Operations,G2,711,1,0.451558,0.775943,0.238710
5,Samara Sharma,NaN,62000.0,NaN,Sales,G3,649,2,0.172522,0.702830,-0.161290
6,Joaquin Fleiman,54.0,NaN,F,Operations,G3,53,2,-2.509823,0.000000,-4.006452
7,Juana Wilkis,54.0,52000.0,F,Finance,G3,901,2,1.306668,1.000000,1.464516
8,Leonardo Doberti,23.0,98000.0,M,Sales,G4,709,3,0.442557,0.773585,0.225806

## **Transformación de las características de los datos**

In [44]:
empleados = pd.read_csv(url2)

In [45]:
def grado_performance(performance):
    if performance >= 700:
        return "A"
    elif performance < 700 and performance >= 500:
        return "B"
    else:
        return "C"

In [46]:
empleados["grado_performance"] = empleados.performance.apply(grado_performance)

In [47]:
empleados

,nombre,edad,sueldo,sexo,sector,nivel,performance,grado_performance
0,Alan Smith,45.0,NaN,NaN,Operations,G3,723,A
1,Sandro Kumar,NaN,16000.0,F,Finance,G0,520,B
2,Jacinto Morgan,32.0,35000.0,M,Finance,G2,674,B
3,Ernesto Chin,45.0,65000.0,F,Sales,G3,556,B
4,Fernanda Patel,30.0,42000.0,F,Operations,G2,711,A
5,Samara Sharma,NaN,62000.0,NaN,Sales,G3,649,B
6,Joaquin Fleiman,54.0,NaN,F,Operations,G3,53,C
7,Juana Wilkis,54.0,52000.0,F,Finance,G3,901,A
8,Leonardo Doberti,23.0,98000.0,M,Sales,G4,709,A

In [48]:
empleados = pd.read_csv(url2)

In [49]:
empleados.performance = empleados.performance.apply(grado_performance)

In [50]:
empleados

             nombre  edad   sueldo sexo      sector nivel performance
0        Alan Smith  45.0      NaN  NaN  Operations    G3           A
1      Sandro Kumar   NaN  16000.0    F     Finance    G0           B
2    Jacinto Morgan  32.0  35000.0    M     Finance    G2           B
3      Ernesto Chin  45.0  65000.0    F       Sales    G3           B
4    Fernanda Patel  30.0  42000.0    F  Operations    G2           A
5     Samara Sharma   NaN  62000.0  NaN       Sales    G3           B
6   Joaquin Fleiman  54.0      NaN    F  Operations    G3           C
7      Juana Wilkis  54.0  52000.0    F     Finance    G3           A
8  Leonardo Doberti  23.0  98000.0    M       Sales    G4           A

## **Division de las columnas**

In [51]:
empleados = pd.read_csv(url2)

In [52]:
empleados["primer_nombre"] = empleados.nombre.str.split(" ").map(lambda var: var[0])

In [53]:
empleados["ultimo_nombre"] = empleados.nombre.str.split(" ").map(lambda var: var[1])

In [54]:
empleados

,nombre,edad,sueldo,sexo,sector,nivel,performance,primer_nombre,ultimo_nombre
0,Alan Smith,45.0,NaN,NaN,Operations,G3,723,Alan,Smith
1,Sandro Kumar,NaN,16000.0,F,Finance,G0,520,Sandro,Kumar
2,Jacinto Morgan,32.0,35000.0,M,Finance,G2,674,Jacinto,Morgan
3,Ernesto Chin,45.0,65000.0,F,Sales,G3,556,Ernesto,Chin
4,Fernanda Patel,30.0,42000.0,F,Operations,G2,711,Fernanda,Patel
5,Samara Sharma,NaN,62000.0,NaN,Sales,G3,649,Samara,Sharma
6,Joaquin Fleiman,54.0,NaN,F,Operations,G3,53,Joaquin,Fleiman
7,Juana Wilkis,54.0,52000.0,F,Finance,G3,901,Juana,Wilkis
8,Leonardo Doberti,23.0,98000.0,M,Sales,G4,709,Leonardo,Doberti